In [1]:
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from optbinning import BinningProcess

In [2]:
train_data = pd.read_csv('data/credit_scoring_data/train 2.csv')
test_data = pd.read_csv('data/credit_scoring_data/test 2.csv')

/var/folders/3f/9mw8q0xn58v4947ln1hhc4mr0000gn/T/ipykernel_30105/1488526157.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data = pd.read_csv('data/credit_scoring_data/train 2.csv')

In [3]:
train_data.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

In [5]:
train_data['Customer_ID'].nunique()

12500

In [6]:
train_data['Customer_ID'].unique()

array(['CUS_0xd40', 'CUS_0x21b1', 'CUS_0x2dbc', ..., 'CUS_0xaf61',
       'CUS_0x8600', 'CUS_0x942c'], shape=(12500,), dtype=object)

In [7]:
sample = train_data[train_data['Customer_ID'] == 'CUS_0x21b1']
sample

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
8,0x160e,CUS_0x21b1,January,Rick Rothackerj,28_,004-07-5839,_______,34847.84,3037.986667,2,...,Good,605.03,24.464031,26 Years and 7 Months,No,18.816215,104.291825168246,Low_spent_Small_value_payments,470.69062692529184,Standard
9,0x160f,CUS_0x21b1,February,Rick Rothackerj,28,004-07-5839,Teacher,34847.84,3037.986667,2,...,Good,605.03,38.550848,26 Years and 8 Months,No,18.816215,40.39123782853101,High_spent_Large_value_payments,484.5912142650067,Good
10,0x1610,CUS_0x21b1,March,Rick Rothackerj,28,004-07-5839,Teacher,34847.84_,3037.986667,2,...,_,605.03,33.224951,26 Years and 9 Months,No,18.816215,58.51597569589465,High_spent_Large_value_payments,466.46647639764313,Standard
11,0x1611,CUS_0x21b1,April,Rick Rothackerj,28,004-07-5839,Teacher,34847.84,NaN,2,...,Good,605.03,39.182656,26 Years and 10 Months,No,18.816215,99.30622796053305,Low_spent_Medium_value_payments,465.6762241330048,Good
12,0x1612,CUS_0x21b1,May,Rick Rothackerj,28,004-07-5839,Teacher,34847.84,3037.986667,2,...,Good,605.03,34.977895,26 Years and 11 Months,No,18.816215,130.11542024292334,Low_spent_Small_value_payments,444.8670318506144,Good
13,0x1613,CUS_0x21b1,June,Rick Rothackerj,28,004-07-5839,Teacher,34847.84,3037.986667,2,...,Good,605.03,33.381010,27 Years and 0 Months,No,18.816215,43.477190144355745,High_spent_Large_value_payments,481.505261949182,Good
14,0x1614,CUS_0x21b1,July,Rick Rothackerj,28,004-07-5839,Teacher,34847.84,NaN,2,...,Good,605.03,31.131702,27 Years and 1 Months,NM,18.816215,70.10177420755677,High_spent_Medium_value_payments,464.8806778859809,Good
15,0x1615,CUS_0x21b1,August,Rick Rothackerj,28,004-07-5839,Teacher,34847.84,3037.986667,2,...,Good,605.03,32.933856,27 Years and 2 Months,No,18.816215,218.90434353388733,Low_spent_Small_value_payments,356.07810855965045,Good

In [8]:
long_data = train_data.copy()

In [9]:
long_data = long_data.drop(columns = ['SSN', 'Name', 'ID'])

In [10]:
cat_cols = long_data.select_dtypes(include = ['object', 'string']).columns
cat_cols

Index(['Customer_ID', 'Month', 'Age', 'Occupation', 'Annual_Income',
       'Num_of_Loan', 'Type_of_Loan', 'Num_of_Delayed_Payment',
       'Changed_Credit_Limit', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_History_Age', 'Payment_of_Min_Amount',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')

In [11]:
long_data['Credit_Score'].value_counts()

Credit_Score
Standard    53174
Poor        28998
Good        17828
Name: count, dtype: int64

In [12]:
# str_to_num = ['Age', 'Annual_Income', 'Num_of_Loan','Num_of_Delayed_Payment', 'Credit_History_Age', 
#               'Amount_invested_monthly', 'Monthly_Balance', 'month2_balance', 'month3_balance',
#               'Changed_Credit_Limit', 'Outstanding_Debt']

In [13]:
long_data['Credit_History_Age'].unique()

array(['22 Years and 1 Months', nan, '22 Years and 3 Months',
       '22 Years and 4 Months', '22 Years and 5 Months',
       '22 Years and 6 Months', '22 Years and 7 Months',
       '26 Years and 7 Months', '26 Years and 8 Months',
       '26 Years and 9 Months', '26 Years and 10 Months',
       '26 Years and 11 Months', '27 Years and 0 Months',
       '27 Years and 1 Months', '27 Years and 2 Months',
       '17 Years and 9 Months', '17 Years and 10 Months',
       '17 Years and 11 Months', '18 Years and 1 Months',
       '18 Years and 2 Months', '18 Years and 3 Months',
       '18 Years and 4 Months', '17 Years and 3 Months',
       '17 Years and 4 Months', '17 Years and 5 Months',
       '17 Years and 6 Months', '17 Years and 7 Months',
       '17 Years and 8 Months', '30 Years and 8 Months',
       '30 Years and 9 Months', '30 Years and 10 Months',
       '30 Years and 11 Months', '31 Years and 0 Months',
       '31 Years and 1 Months', '31 Years and 2 Months',
       '31 Years and 3 Months', '32 Years and 0 Months',
       '32 Years and 2 Months', '32 Years and 3 Months',
       '32 Years and 5 Months', '32 Years and 6 Months',
       '30 Years and 7 Months', '14 Years and 8 Months',
       '14 Years and 9 Months', '14 Years and 10 Months',
       '14 Years and 11 Months', '15 Years and 0 Months',
       '15 Years and 1 Months', '15 Years and 2 Months',
       '21 Years and 4 Months', '21 Years and 5 Months',
       '21 Years and 6 Months', '21 Years and 7 Months',
       '21 Years and 8 Months', '21 Years and 9 Months',
       '21 Years and 10 Months', '21 Years and 11 Months',
       '26 Years and 6 Months', '19 Years and 2 Months',
       '19 Years and 3 Months', '19 Years and 4 Months',
       '19 Years and 5 Months', '19 Years and 6 Months',
       '19 Years and 7 Months', '19 Years and 8 Months',
       '25 Years and 5 Months', '25 Years and 6 Months',
       '25 Years and 7 Months', '25 Years and 8 Months',
       '25 Years and 9 Months', '25 Years and 10 Months',
       '25 Years and 11 Months', '26 Years and 0 Months',
       '27 Years and 3 Months', '27 Years and 4 Months',
       '27 Years and 5 Months', '8 Years and 11 Months',
       '9 Years and 0 Months', '9 Years and 1 Months',
       '9 Years and 2 Months', '9 Years and 3 Months',
       '9 Years and 4 Months', '9 Years and 6 Months',
       '18 Years and 5 Months', '18 Years and 6 Months',
       '18 Years and 8 Months', '18 Years and 9 Months',
       '16 Years and 10 Months', '16 Years and 11 Months',
       '17 Years and 0 Months', '17 Years and 1 Months',
       '17 Years and 2 Months', '29 Years and 2 Months',
       '29 Years and 3 Months', '29 Years and 4 Months',
       '29 Years and 6 Months', '29 Years and 8 Months',
       '29 Years and 9 Months', '6 Years and 5 Months',
       '6 Years and 6 Months', '6 Years and 7 Months',
       '6 Years and 8 Months', '6 Years and 9 Months',
       '6 Years and 10 Months', '6 Years and 11 Months',
       '7 Years and 0 Months', '27 Years and 6 Months',
       '27 Years and 7 Months', '27 Years and 8 Months',
       '27 Years and 9 Months', '18 Years and 7 Months',
       '19 Years and 9 Months', '19 Years and 10 Months',
       '10 Years and 1 Months', '10 Years and 2 Months',
       '10 Years and 3 Months', '10 Years and 4 Months',
       '10 Years and 5 Months', '10 Years and 6 Months',
       '10 Years and 7 Months', '10 Years and 8 Months',
       '32 Years and 9 Months', '32 Years and 10 Months',
       '32 Years and 11 Months', '33 Years and 0 Months',
       '33 Years and 1 Months', '33 Years and 4 Months',
       '12 Years and 3 Months', '12 Years and 4 Months',
       '12 Years and 5 Months', '12 Years and 6 Months',
       '12 Years and 7 Months', '12 Years and 8 Months',
       '12 Years and 10 Months', '12 Years and 9 Months',
       '13 Years and 8 Months', '13 Years and 11 Months',
       '14 Years and 0 Months', '14 Years and 1 Months',
       '14 Years and 2 Months', '14 Years and 3 Months',
       '30 Years and 3 Months', '30 Years and 4 Months',
       '30 Years and 5 Months', '30 Years and 6 Months',
       '8 Years and 9 Months', '8 Years and 10 Months',
       '18 Years and 10 Months', '18 Years and 11 Months',
       '19 Years and 0 Months', '19 Years and 1 Months',
       '8 Years and 8 Months', '13 Years and 1 Months',
       '13 Years and 2 Months', '13 Years and 3 Months',
       '13 Years and 5 Months', '13 Years and 6 Months',
       '13 Years and 7 Months', '22 Years and 0 Months',
       '26 Years and 1 Months', '26 Years and 2 Months',
       '13 Years and 4 Months', '13 Years and 9 Months',
       '27 Years and 11 Months', '28 Years and 0 Months',
       '28 Years and 1 Months', '28 Years and 2 Months',
       '28 Years and 3 Months', '28 Years and 4 Months',
       '28 Years and 5 Months', '28 Years and 6 Months',
       '7 Years and 10 Months', '7 Years and 11 Months',
       '8 Years and 0 Months', '8 Years and 1 Months',
       '8 Years and 2 Months', '8 Years and 3 Months',
       '8 Years and 4 Months', '8 Years and 5 Months',
       '24 Years and 3 Months', '24 Years and 4 Months',
       '24 Years and 5 Months', '24 Years and 6 Months',
       '24 Years and 7 Months', '24 Years and 8 Months',
       '24 Years and 9 Months', '1 Years and 2 Months',
       '1 Years and 3 Months', '1 Years and 4 Months',
       '1 Years and 5 Months', '1 Years and 6 Months',
       '1 Years and 7 Months', '1 Years and 8 Months',
       '10 Years and 11 Months', '11 Years and 0 Months',
       '11 Years and 1 Months', '11 Years and 2 Months',
       '11 Years and 3 Months', '11 Years and 4 Months',
       '11 Years and 5 Months', '11 Years and 6 Months',
       '19 Years and 11 Months', '20 Years and 0 Months',
       '20 Years and 1 Months', '10 Years and 9 Months',
       '10 Years and 10 Months', '14 Years and 4 Months',
       '14 Years and 5 Months', '14 Years and 6 Months',
       '20 Years and 8 Months', '20 Years and 9 Months',
       '20 Years and 10 Months', '20 Years and 11 Months',
       '21 Years and 0 Months', '21 Years and 1 Months',
       '21 Years and 2 Months', '21 Years and 3 Months',
       '0 Years and 4 Months', '0 Years and 5 Months',
       '0 Years and 6 Months', '0 Years and 8 Months',
       '0 Years and 9 Months', '0 Years and 10 Months',
       '31 Years and 7 Months', '31 Years and 8 Months',
       '31 Years and 9 Months', '31 Years and 10 Months',
       '31 Years and 11 Months', '32 Years and 1 Months',
       '12 Years and 11 Months', '13 Years and 0 Months',
       '27 Years and 10 Months', '11 Years and 7 Months',
       '11 Years and 8 Months', '11 Years and 9 Months',
       '11 Years and 10 Months', '24 Years and 10 Months',
       '24 Years and 11 Months', '25 Years and 0 Months',
       '25 Years and 1 Months', '25 Years and 2 Months',
       '25 Years and 3 Months', '18 Years and 0 Months',
       '31 Years and 4 Months', '31 Years and 5 Months',
       '31 Years and 6 Months', '5 Years and 2 Months',
       '5 Years and 3 Months', '5 Years and 4 Months',
       '5 Years and 5 Months', '5 Years and 6 Months',
       '5 Years and 7 Months', '5 Years and 8 Months',
       '5 Years and 9 Months', '2 Years and 11 Months',
       '3 Years and 0 Months', '3 Years and 1 Months',
       '3 Years and 2 Months', '3 Years and 3 Months',
       '3 Years and 4 Months', '3 Years and 5 Months',
       '3 Years and 6 Months', '16 Years and 4 Months',
       '16 Years and 5 Months', '16 Years and 6 Months',
       '16 Years and 7 Months', '16 Years and 8 Months',
       '16 Years and 9 Months', '22 Years and 11 Months',
       '23 Years and 0 Months', '23 Years and 2 Months',
       '23 Years and 3 Months', '23 Years and 4 Months',
       '23 Years and 5 Months', '23 Years and 6 Months',
       '8 Years and 6 Months', '8 Years and 7 Months',
       '4 Years and 5 Months', '4 Years and 6 Months',
       '4 Years and 7 Months', '4 Years and 8 Months',
       '4 Years and 9 Months', '4 Years and 10 Months',
       '4 Years and 11 Months', '5 Years and 0 Months',
       '32 Years and 8 Months', '33 Years and 2 Months',
       '33 Years and 3 Months', '12 Years and 2 Months',
       '32 Years and 4 Months', '29 Years and 11 Months',
       '30 Years and 0 Months', '30 Years and 2 Months',
       '26 Years and 3 Months', '26 Years and 4 Months',
       '26 Years and 5 Months', '7 Years and 6 Months',
       '7 Years and 7 Months', '7 Years and 8 Months',
       '7 Years and 9 Months', '28 Years and 7 Months',
       '28 Years and 8 Months', '28 Years and 9 Months',
       '28 Years and 10 Months', '29 Years and 5 Months',
       '29 Years and 7 Months', '20 Years and 2 Months',
       '20 Years and 3 Months', '20 Years and 4 Months',
       '20 Years and 5 Months', '20 Years and 6 Months',
       '20 Years and 7 Months', '28 Years and 11 Months',
       '29 Years and 0 Months', '13 Years and 10 Months',
       '1 Years and 9 Months', '1 Years and 10 Months',
       '1 Years and 11 Months', '33 Years and 5 Months',
       '33 Years and 6 Months', '33 Years and 7 Months',
       '33 Years and 8 Months', '29 Years and 1 Months',
       '5 Years and 1 Months', '5 Years and 10 Months',
       '5 Years and 11 Months', '6 Years and 0 Months',
       '6 Years and 1 Months', '6 Years and 2 Months',
       '6 Years and 3 Months', '22 Years and 9 Months',
       '22 Years and 10 Months', '23 Years and 1 Months',
       '22 Years and 2 Months', '15 Years and 4 Months',
       '15 Years and 5 Months', '15 Years and 6 Months',
       '15 Years and 7 Months', '15 Years and 8 Months',
       '15 Years and 9 Months', '15 Years and 10 Months',
       '15 Years and 11 Months', '2 Years and 3 Months',
       '2 Years and 4 Months', '2 Years and 5 Months',
       '2 Years and 6 Months', '2 Years and 7 Months',
       '2 Years and 8 Months', '2 Years and 9 Months',
       '2 Years and 10 Months', '2 Years and 0 Months',
       '16 Years and 2 Months', '16 Years and 3 Months',
       '22 Years and 8 Months', '9 Years and 5 Months',
       '9 Years and 7 Months', '9 Years and 8 Months',
       '9 Years and 9 Months', '11 Years and 11 Months',
       '12 Years and 0 Months', '12 Years and 1 Months',
       '24 Years and 2 Months', '16 Years and 0 Months',
       '16 Years and 1 Months', '14 Years and 7 Months',
       '25 Years and 4 Months', '15 Years and 3 Months',
       '7 Years and 1 Months', '7 Years and 2 Months',
       '7 Years and 3 Months', '7 Years and 4 Months',
       '7 Years and 5 Months', '23 Years and 7 Months',
       '23 Years and 8 Months', '23 Years and 9 Months',
       '30 Years and 1 Months', '29 Years and 10 Months',
       '9 Years and 10 Months', '9 Years and 11 Months',
       '10 Years and 0 Months', '2 Years and 2 Months',
       '23 Years and 10 Months', '23 Years and 11 Months',
       '24 Years and 0 Months', '24 Years and 1 Months',
       '6 Years and 4 Months', '0 Years and 1 Months',
       '0 Years and 2 Months', '0 Years and 3 Months',
       '0 Years and 7 Months', '3 Years and 8 Months',
       '32 Years and 7 Months', '3 Years and 7 Months',
       '3 Years and 9 Months', '3 Years and 10 Months',
       '0 Years and 11 Months', '1 Years and 0 Months',
       '1 Years and 1 Months', '4 Years and 4 Months',
       '3 Years and 11 Months', '4 Years and 0 Months',
       '4 Years and 1 Months', '4 Years and 2 Months',
       '4 Years and 3 Months', '2 Years and 1 Months'], dtype=object)

In [14]:
import re

def period_to_months(row):
    if pd.isna(row):
        return 0
    years = re.search(r'(\d+)\s*Year', row)
    months = re.search(r'(\d+)\s*Month', row)
    num_years = int(years.group(1)) if years else 0
    num_months = int(months.group(1)) if months else 0
    total_months = (num_years * 12 )+ num_months
    return int(total_months)

In [15]:
long_data['Credit_History_Age'] = long_data['Credit_History_Age'].apply(period_to_months)

In [16]:
long_data['Credit_History_Age'].dtype

dtype('int64')

In [17]:
long_data['Credit_History_Age'][:10]

0    265
1      0
2    267
3    268
4    269
5    270
6    271
7      0
8    319
9    320
Name: Credit_History_Age, dtype: int64

In [18]:
# long_data['Credit_History_Age'] = long_data['Credit_History_Age'].str.strip('.').astype(float)

In [19]:
# long_data['Credit_History_Age'].unique()
str_to_num = ['Age', 'Annual_Income', 'Num_of_Loan','Num_of_Delayed_Payment',
              'Amount_invested_monthly', 'Monthly_Balance',
            #   , 'month2_balance', 'month3_balance',
              'Changed_Credit_Limit', 'Outstanding_Debt']

In [20]:
long_data['Outstanding_Debt'].unique()

array(['809.98', '605.03', '1303.01', ..., '3571.7_', '3571.7', '502.38'],
      shape=(13178,), dtype=object)

In [21]:
long_data[str_to_num] = long_data[str_to_num].apply(
    lambda col: pd.to_numeric(
        col.astype(str).str.replace('_', '', regex=False),
        errors='coerce'
    )
)

In [22]:
long_data['Annual_Income'].unique()

array([ 19114.12,  34847.84, 143162.64, ...,  37188.1 ,  20002.88,
        39628.99], shape=(13487,))

In [23]:
long_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Customer_ID               100000 non-null  object
 1   Month                     100000 non-null  object
 2   Age                       100000 non-null  int64
 3   Occupation                100000 non-null  object
 4   Annual_Income             100000 non-null  float64
 5   Monthly_Inhand_Salary     84998 non-null   float64
 6   Num_Bank_Accounts         100000 non-null  int64
 7   Num_Credit_Card           100000 non-null  int64
 8   Interest_Rate             100000 non-null  int64
 9   Num_of_Loan               100000 non-null  int64
 10  Type_of_Loan              88592 non-null   object
 11  Delay_from_due_date       100000 non-null  int64
 12  Num_of_Delayed_Payment    92998 non-null   float64
 13  Changed_Credit_Limit      97909 non-null   float64
 14  Num_Credit_Inquiries      98035 non-null   float64
 15  Credit_Mix                100000 non-null  object
 16  Outstanding_Debt          100000 non-null  float64
 17  Credit_Utilization_Ratio  100000 non-null  float64
 18  Credit_History_Age        100000 non-null  int64
 19  Payment_of_Min_Amount     100000 non-null  object
 20  Total_EMI_per_month       100000 non-null  float64
 21  Amount_invested_monthly   95521 non-null   float64
 22  Payment_Behaviour         100000 non-null  object
 23  Monthly_Balance           98800 non-null   float64
 24  Credit_Score              100000 non-null  object
dtypes: float64(10), int64(7), object(8)
memory usage: 19.1+ MB

In [24]:
cat_cols = long_data.select_dtypes(include = ['object','string']).columns

## Feature Engineering

In [25]:
cat_cols

Index(['Customer_ID', 'Month', 'Occupation', 'Type_of_Loan', 'Credit_Mix',
       'Payment_of_Min_Amount', 'Payment_Behaviour', 'Credit_Score'],
      dtype='object')

In [26]:
long_data['Type_of_Loan'] = long_data['Type_of_Loan'].str.replace('and', '', regex=False)

In [27]:
long_data['Type_of_Loan'].unique().tolist()

['Auto Loan, Credit-Builder Loan, Personal Loan,  Home Equity Loan',
 'Credit-Builder Loan',
 'Auto Loan, Auto Loan,  Not Specified',
 'Not Specified',
 nan,
 'Credit-Builder Loan,  Mortgage Loan',
 'Not Specified, Auto Loan,  Student Loan',
 'Personal Loan, Debt Consolidation Loan,  Auto Loan',
 'Not Specified,  Payday Loan',
 'Credit-Builder Loan, Personal Loan,  Auto Loan',
 'Payday Loan,  Payday Loan',
 'Not Specified, Student Loan,  Personal Loan',
 'Personal Loan, Payday Loan, Student Loan, Auto Loan, Home Equity Loan, Student Loan,  Payday Loan',
 'Not Specified, Student Loan, Student Loan, Credit-Builder Loan,  Auto Loan',
 'Payday Loan,  Home Equity Loan',
 'Credit-Builder Loan, Not Specified, Mortgage Loan, Payday Loan, Credit-Builder Loan,  Personal Loan',
 'Mortgage Loan, Debt Consolidation Loan, Payday Loan, Auto Loan,  Not Specified',
 'Credit-Builder Loan, Mortgage Loan, Mortgage Loan, Credit-Builder Loan,  Student Loan',
 'Not Specified, Student Loan,  Student Loan',
 'Payday Loan, Not Specified, Credit-Builder Loan, Debt Consolidation Loan, Payday Loan, Not Specified, Student Loan,  Student Loan',
 'Home Equity Loan, Credit-Builder Loan,  Home Equity Loan',
 'Home Equity Loan, Credit-Builder Loan, Credit-Builder Loan, Home Equity Loan, Debt Consolidation Loan, Mortgage Loan,  Auto Loan',
 'Debt Consolidation Loan',
 'Payday Loan, Not Specified,  Auto Loan',
 'Auto Loan, Student Loan, Payday Loan, Payday Loan, Mortgage Loan,  Debt Consolidation Loan',
 'Auto Loan,  Home Equity Loan',
 'Payday Loan, Not Specified, Student Loan, Credit-Builder Loan, Credit-Builder Loan,  Payday Loan',
 'Mortgage Loan,  Payday Loan',
 'Mortgage Loan, Personal Loan, Home Equity Loan, Personal Loan, Mortgage Loan,  Personal Loan',
 'Personal Loan, Credit-Builder Loan, Debt Consolidation Loan, Not Specified,  Not Specified',
 'Home Equity Loan, Mortgage Loan, Credit-Builder Loan,  Payday Loan',
 'Home Equity Loan, Credit-Builder Loan, Personal Loan,  Mortgage Loan',
 'Mortgage Loan,  Not Specified',
 'Credit-Builder Loan, Payday Loan, Home Equity Loan, Credit-Builder Loan, Personal Loan,  Credit-Builder Loan',
 'Credit-Builder Loan, Personal Loan, Credit-Builder Loan,  Home Equity Loan',
 'Personal Loan, Mortgage Loan,  Payday Loan',
 'Student Loan, Home Equity Loan, Payday Loan, Debt Consolidation Loan, Not Specified, Not Specified, Personal Loan,  Payday Loan',
 'Credit-Builder Loan, Personal Loan, Credit-Builder Loan, Mortgage Loan, Personal Loan, Payday Loan, Payday Loan, Payday Loan,  Student Loan',
 'Auto Loan,  Payday Loan',
 'Student Loan, Auto Loan, Personal Loan, Auto Loan, Credit-Builder Loan, Payday Loan, Home Equity Loan, Auto Loan,  Personal Loan',
 'Personal Loan,  Student Loan',
 'Auto Loan, Payday Loan, Debt Consolidation Loan, Debt Consolidation Loan, Not Specified,  Student Loan',
 'Not Specified, Student Loan, Auto Loan, Home Equity Loan,  Mortgage Loan',
 'Student Loan, Payday Loan, Personal Loan, Not Specified, Mortgage Loan, Student Loan, Debt Consolidation Loan,  Debt Consolidation Loan',
 'Personal Loan, Student Loan, Home Equity Loan, Not Specified, Home Equity Loan, Home Equity Loan,  Mortgage Loan',
 'Not Specified, Personal Loan, Credit-Builder Loan,  Home Equity Loan',
 'Auto Loan, Personal Loan, Mortgage Loan, Auto Loan, Student Loan, Auto Loan, Mortgage Loan, Student Loan,  Auto Loan',
 'Auto Loan, Credit-Builder Loan, Mortgage Loan, Debt Consolidation Loan, Debt Consolidation Loan, Not Specified,  Debt Consolidation Loan',
 'Mortgage Loan, Personal Loan,  Not Specified',
 'Credit-Builder Loan, Home Equity Loan, Home Equity Loan, Student Loan, Student Loan, Home Equity Loan,  Credit-Builder Loan',
 'Not Specified, Credit-Builder Loan, Payday Loan,  Credit-Builder Loan',
 'Debt Consolidation Loan, Home Equity Loan,  Personal Loan',
 'Student Loan, Student Loan, Student Loan, Debt Consolidation Loan, Home Equity Loan, Debt Consolidation Loan,  Payday Loan',
 'Home Equity Loan, Credit-Builder Loan, Debt Consolidation Loan, Payday Loan,  Home Equity Loan',
 'Home Equity Loan, Mortgage Loan, Debt Consolidation Loan, Home Equity Loan, Personal Loan,  Personal Loan',
 'Not Specified, Payday Loan, Auto Loan,  Home Equity Loan',
 'Mortgage Loan, Student Loan, Not Specified,  Mortgage Loan',
 'Mortgage Loan, Auto Loan, Personal Loan, Student Loan, Home Equity Loan,  Student Loan',
 'Payday Loan,  Not Specified',
 'Auto Loan, Not Specified, Payday Loan, Mortgage Loan, Personal Loan, Payday Loan,  Personal Loan',
 'Home Equity Loan,  Student Loan',
 'Personal Loan, Payday Loan, Auto Loan, Debt Consolidation Loan,  Debt Consolidation Loan',
 'Auto Loan',
 'Credit-Builder Loan, Mortgage Loan, Auto Loan, Auto Loan, Not Specified,  Home Equity Loan',
 'Student Loan, Auto Loan, Auto Loan,  Payday Loan',
 'Home Equity Loan',
 'Payday Loan, Auto Loan, Credit-Builder Loan, Debt Consolidation Loan, Credit-Builder Loan, Auto Loan,  Personal Loan',
 'Student Loan,  Auto Loan',
 'Student Loan',
 'Auto Loan, Auto Loan, Auto Loan,  Personal Loan',
 'Mortgage Loan,  Mortgage Loan',
 'Personal Loan, Payday Loan,  Auto Loan',
 'Mortgage Loan, Not Specified, Credit-Builder Loan, Debt Consolidation Loan, Not Specified, Mortgage Loan,  Student Loan',
 'Mortgage Loan, Auto Loan, Not Specified, Student Loan,  Payday Loan',
 'Student Loan, Mortgage Loan, Not Specified,  Not Specified',
 'Home Equity Loan, Credit-Builder Loan, Student Loan,  Personal Loan',
 'Student Loan, Not Specified, Not Specified, Credit-Builder Loan, Student Loan, Mortgage Loan, Not Specified,  Student Loan',
 'Debt Consolidation Loan, Home Equity Loan, Auto Loan, Home Equity Loan,  Debt Consolidation Loan',
 'Personal Loan,  Payday Loan',
 'Student Loan, Debt Consolidation Loan, Credit-Builder Loan,  Home Equity Loan',
 'Personal Loan, Debt Consolidation Loan, Debt Consolidation Loan,  Student Loan',
 'Student Loan, Personal Loan, Home Equity Loan, Home Equity Loan,  Auto Loan',
 'Student Loan, Student Loan, Debt Consolidation Loan,  Mortgage Loan',
 'Auto Loan, Auto Loan, Student Loan,  Home Equity Loan',
 'Mortgage Loan, Student Loan, Student Loan, Payday Loan, Mortgage Loan,  Debt Consolidation Loan',
 'Not Specified, Debt Consolidation Loan, Home Equity Loan,  Mortgage Loan',
 'Debt Consolidation Loan, Debt Consolidation Loan,  Credit-Builder Loan',
 'Student Loan, Debt Consolidation Loan,  Auto Loan',
 'Mortgage Loan, Student Loan,  Mortgage Loan',
 'Auto Loan, Auto Loan, Credit-Builder Loan, Not Specified, Not Specified,  Not Specified',
 'Auto Loan,  Auto Loan',
 'Payday Loan,  Debt Consolidation Loan',
 'Home Equity Loan, Credit-Builder Loan, Personal Loan,  Not Specified',
 'Mortgage Loan, Home Equity Loan, Personal Loan, Payday Loan, Not Specified, Student Loan, Payday Loan,  Payday Loan',
 'Payday Loan, Payday Loan, Not Specified, Student Loan, Mortgage Loan, Payday Loan, Mortgage Loan,  Credit-Builder Loan',
 'Personal Loan, Student Loan, Payday Loan, Personal Loan, Not Specified, Not Specified, Mortgage Loan, Not Specified,  Home Equity Loan',
 'Debt Consolidation Loan, Credit-Builder Loan, Credit-Builder Loan, Personal Loan,  Not Specified',
 'Debt Consolidation Loan,  Auto Loan',
 'Not Specified, Student Loan, Auto Loan, Payday Loan,  Auto Loan',
 'Home Equity Loan, Mortgage Loan, Credit-Builder Loan,  Debt Consolidation Loan',
 'Home Equity Loan, Debt Consolidation Loan, Personal Loan,  Payday Loan',
 'Not Specified, Payday Loan, Payday Loan,  Debt Consolidation Loan',
 'Payday Loan, Not Specified,  Mortgage Loan',
 'Mortgage Loan, Mortgage Loan, Not Specified, Personal Loan, Credit-Builder Loan,  Debt Consolidation Loan',
 'Not Specified, Student Loan, Home Equity Loan, Personal Loan,  Personal Loan',
 'Auto Loan,  Credit-Builder Loan',
 'Credit-Builder Loan, Debt Consolidation Loan, Payday Loan, Personal Loan, Not Specified,  Payday Loan',
 'Personal Loan, Home Equity Loan,  Debt Consolidation Loan',
 'Personal Loan',
 'Not Specified, Home Equity Loan,  Home Equity Loan',
 'Student Loan, Home Equity Loan, Not Specified,  Credit-Builder Loan',
 'Credit-Builder Loan, Auto Loan, Student Loan, Student Loan, Personal Loan, Personal Loan,  Auto Loan',
 'Student Loan,  Not Specified',
 'Not Specified, Not Specified, Not Specified, Mortgage Loan, Student Loan,  Auto Loan',
 'Home Equity Loan, Auto Loan,  Home Equity Loan',
 'Mortgage Loan, Payday Loan, Auto Loan, Not Specified, Credit-Builder Loan,  Home Equity Loan',
 'Home Equity Loan,  Not Specified',
 'Credit-Builder Loan, Auto Loan, Credit-Builder Loan, Student Loan, Personal Loan, Not Specified,  Mortgage Loan',
 'Payday Loan',
 'Debt Consolidation Loan, Home Equity Loan,  Student Loan',
 'Credit-Builder Loan, Student Loan, Mortgage Loan,  Mortgage Loan',
 'Auto Loan, Student Loan,  Student Loan',
 'Personal Loan, Payday Loan,  Personal Loan',
 'Debt Consolidation Loan,  Home Equity Loan',
 'Not Specified, Student Loan,  Not Specified',
 'Personal Loan, Payday Loan, Student Loan, Not Specified,  Not Specified',
 'Student Loan, Credit-Builder Loan, Home Equity Loan, Personal Loan, Home Equity Loan,  Mortgage Loan',
 'Home Equity Loan, Mortgage Loan, Credit-Builder Loan, Mortgage Loan, Student Loan,  Student Loan',
 'Home Equity Loan, Debt Consolidation Loan, Auto Loan, Debt Consolidation Loan, Payday Loan, Student Loan, Personal Loan, Payday Loan,  Credit-Builder Loan',
 'Mortgage Loan,  Personal Loan',
 'Mortgage Loan, Credit-Builder Loan, Student Loan, Debt Consolidation Loan, Mortgage Loan,  Auto Loan',
 'Mortgage Loan,  Student Loan',
 'Debt Consolidation Loan, Home Equity Loan,  Not Specified',
 'Student Loan,  Mortgage Loan',
 'Credit-Builder Loan, Home Equity Loan, Personal Loan, Auto Loan, Personal Loan, Auto Loan,  Credit-Builder Loan',
 'Home Equity Loan, Personal Loan, Credit-Builder Loan,  Credit-Builder Loan',
 'Not Specified, Credit-Builder Loan, Not Specified, Credit-Builder Loan, Auto Loan, Payday Loan, Mortgage Loan,  Credit-Builder Loan',
 'Home Equity Loan, Home Equity Loan, Payday Loan,  Mortgage Loan',
 'Personal Loan, Personal Loan, Personal Loan,  Student Loan',
 'Personal Loan, Home Equity Loan, Credit-Builder Loan, Not Specified, Home Equity Loan, Personal Loan,  Personal Loan',
 'Home Equity Loan, Personal Loan,  Home Equity Loan',
 'Payday Loan,  Credit-Builder Loan',
 'Payday Loan, Personal Loan, Payday Loan,  Mortgage Loan',
 'Credit-Builder Loan,  Personal Loan',
 'Student Loan, Credit-Builder Loan,  Not Specified',
 'Not Specified, Payday Loan, Home Equity Loan, Auto Loan, Home Equity Loan, Student Loan, Credit-Builder Loan,  Personal Loan',
 'Payday Loan, Home Equity Loan, Not Specified,  Credit-Builder Loan',
 'Debt Consolidation Loan, Mortgage Loan, Student Loan, Credit-Builder Loan,  Credit-Builder Loan',
 'Personal Loan, Auto Loan, Personal Loan, Home Equity Loan, Home Equity Loan, Debt Consolidation Loan,  Credit-Builder Loan',
 'Auto Loan, Payday Loan, Mortgage Loan, Student Loan,  Mortgage Loan',
 'Student Loan, Home Equity Loan,  Mortgage Loan',
 'Auto Loan, Credit-Builder Loan, Home Equity Loan, Personal Loan,  Mortgage Loan',
 'Personal Loan, Student Loan, Student Loan,  Not Specified',
 'Auto Loan, Personal Loan,  Payday Loan',
 'Home Equity Loan, Debt Consolidation Loan, Payday Loan,  Credit-Builder Loan',
 'Payday Loan, Auto Loan, Mortgage Loan,  Mortgage Loan',
 'Debt Consolidation Loan, Debt Consolidation Loan, Home Equity Loan, Mortgage Loan, Student Loan, Payday Loan, Debt Consolidation Loan,  Home Equity Loan',
 'Credit-Builder Loan, Not Specified, Debt Consolidation Loan,  Credit-Builder Loan',
 'Mortgage Loan,  Home Equity Loan',
 'Personal Loan,  Mortgage Loan',
 'Credit-Builder Loan, Home Equity Loan,  Home Equity Loan',
 'Credit-Builder Loan, Payday Loan, Home Equity Loan,  Credit-Builder Loan',
 'Credit-Builder Loan, Auto Loan, Auto Loan, Credit-Builder Loan, Credit-Builder Loan,  Credit-Builder Loan',
 'Home Equity Loan, Student Loan,  Debt Consolidation Loan',
 'Mortgage Loan, Personal Loan, Home Equity Loan, Personal Loan, Auto Loan,  Payday Loan',
 'Home Equity Loan,  Mortgage Loan',
 'Personal Loan, Personal Loan, Mortgage Loan, Credit-Builder Loan, Debt Consolidation Loan,  Not Specified',
 'Payday Loan, Payday Loan, Not Specified, Credit-Builder Loan, Student Loan, Payday Loan,  Personal Loan',
 'Debt Consolidation Loan,  Debt Consolidation Loan',
 'Personal Loan, Credit-Builder Loan, Not Specified, Payday Loan, Credit-Builder Loan, Debt Consolidation Loan,  Auto Loan',
 'Student Loan, Personal Loan, Home Equity Loan, Not Specified, Home Equity Loan,  Credit-Builder Loan',
 'Not Specified, Credit-Builder Loan,  Personal Loan',
 'Payday Loan, Mortgage Loan, Payday Loan, Student Loan,  Not Specified',
 'Student Loan, Personal Loan, Not Specified, Not Specified, Debt Consolidation Loan, Debt Consolidation Loan,  Auto Loan',
 'Home Equity Loan, Mortgage Loan, Payday Loan, Personal Loan, Mortgage Loan,  Student Loan',
 'Personal Loan, Personal Loan,  Debt Consolidation Loan',
 'Not Specified,  Mortgage Loan',
 'Payday Loan, Home Equity Loan,  Personal Loan',
 'Student Loan,  Credit-Builder Loan',
 'Student Loan,  Student Loan',
 'Mortgage Loan, Payday Loan, Mortgage Loan, Student Loan,  Credit-Builder Loan',
 'Personal Loan, Student Loan, Payday Loan, Student Loan, Student Loan, Debt Consolidation Loan,  Debt Consolidation Loan',
 'Mortgage Loan, Personal Loan, Payday Loan,  Credit-Builder Loan',
 'Not Specified, Mortgage Loan,  Auto Loan',
 'Debt Consolidation Loan, Auto Loan, Payday Loan,  Payday Loan',
 'Mortgage Loan, Home Equity Loan,  Auto Loan',
 'Payday Loan, Payday Loan, Debt Consolidation Loan, Not Specified, Not Specified, Debt Consolidation Loan, Payday Loan, Credit-Builder Loan,  Auto Loan',
 'Mortgage Loan, Student Loan, Payday Loan, Debt Consolidation Loan,  Auto Loan',
 'Mortgage Loan, Student Loan,  Payday Loan',
 'Home Equity Loan, Mortgage Loan, Payday Loan,  Home Equity Loan',
 'Credit-Builder Loan, Personal Loan,  Mortgage Loan',
 'Home Equity Loan, Payday Loan, Auto Loan,  Auto Loan',
 'Debt Consolidation Loan, Student Loan,  Student Loan',
 'Student Loan, Personal Loan, Auto Loan, Payday Loan, Credit-Builder Loan, Credit-Builder Loan,  Not Specified',
 'Personal Loan, Mortgage Loan, Not Specified,  Payday Loan',
 'Auto Loan,  Student Loan',
 'Mortgage Loan, Payday Loan, Student Loan, Debt Consolidation Loan, Home Equity Loan,  Personal Loan',
 'Auto Loan,  Personal Loan',
 'Mortgage Loan, Student Loan, Debt Consolidation Loan,  Student Loan',
 'Debt Consolidation Loan, Payday Loan, Credit-Builder Loan,  Student Loan',
 'Home Equity Loan, Mortgage Loan,  Student Loan',
 'Credit-Builder Loan,  Not Specified',
 'Auto Loan, Credit-Builder Loan, Home Equity Loan, Not Specified, Student Loan, Payday Loan, Home Equity Loan, Auto Loan,  Student Loan',
 'Payday Loan, Student Loan, Debt Consolidation Loan, Debt Consolidation Loan, Payday Loan, Student Loan,  Personal Loan',
 'Student Loan, Debt Consolidation Loan,  Payday Loan',
 'Home Equity Loan, Mortgage Loan, Mortgage Loan, Not Specified,  Student Loan',
 'Auto Loan, Home Equity Loan, Auto Loan, Home Equity Loan,  Payday Loan',
 'Not Specified, Payday Loan, Mortgage Loan, Not Specified, Payday Loan, Home Equity Loan,  Debt Consolidation Loan',
 'Credit-Builder Loan, Mortgage Loan,  Auto Loan',
 'Payday Loan,  Auto Loan',
 'Credit-Builder Loan, Auto Loan, Home Equity Loan, Not Specified, Debt Consolidation Loan,  Student Loan',
 'Personal Loan, Not Specified, Personal Loan, Personal Loan, Credit-Builder Loan,  Debt Consolidation Loan',
 'Payday Loan, Home Equity Loan, Debt Consolidation Loan,  Student Loan',
 'Not Specified,  Debt Consolidation Loan',
 'Credit-Builder Loan,  Auto Loan',
 'Personal Loan, Mortgage Loan, Not Specified,  Home Equity Loan',
 'Mortgage Loan',
 'Mortgage Loan, Not Specified, Credit-Builder Loan, Auto Loan, Payday Loan, Credit-Builder Loan, Home Equity Loan, Debt Consolidation Loan,  Mortgage Loan',
 'Home Equity Loan,  Credit-Builder Loan',
 'Personal Loan, Credit-Builder Loan, Student Loan, Student Loan, Credit-Builder Loan, Student Loan,  Home Equity Loan',
 'Credit-Builder Loan, Not Specified, Personal Loan, Debt Consolidation Loan, Debt Consolidation Loan, Student Loan, Auto Loan, Student Loan,  Mortgage Loan',
 'Student Loan, Home Equity Loan, Payday Loan,  Home Equity Loan',
 'Mortgage Loan, Home Equity Loan, Home Equity Loan,  Mortgage Loan',
 'Payday Loan, Auto Loan, Personal Loan,  Credit-Builder Loan',
 'Mortgage Loan, Mortgage Loan, Mortgage Loan,  Credit-Builder Loan',
 'Mortgage Loan, Student Loan, Auto Loan, Student Loan, Not Specified, Mortgage Loan,  Student Loan',
 'Personal Loan, Payday Loan, Home Equity Loan, Payday Loan, Mortgage Loan,  Credit-Builder Loan',
 'Auto Loan, Auto Loan, Student Loan,  Credit-Builder Loan',
 'Credit-Builder Loan, Debt Consolidation Loan, Personal Loan, Payday Loan, Payday Loan,  Student Loan',
 'Payday Loan, Debt Consolidation Loan, Not Specified,  Personal Loan',
 'Auto Loan, Mortgage Loan, Credit-Builder Loan,  Home Equity Loan',
 'Home Equity Loan, Not Specified, Home Equity Loan, Home Equity Loan, Debt Consolidation Loan, Debt Consolidation Loan,  Mortgage Loan',
 'Mortgage Loan, Personal Loan, Mortgage Loan, Mortgage Loan, Payday Loan, Home Equity Loan,  Debt Consolidation Loan',
 'Debt Consolidation Loan, Mortgage Loan, Student Loan, Auto Loan,  Payday Loan',
 'Student Loan, Not Specified, Home Equity Loan, Not Specified, Personal Loan,  Personal Loan',
 'Payday Loan, Credit-Builder Loan, Auto Loan,  Personal Loan',
 'Home Equity Loan, Auto Loan, Personal Loan, Auto Loan, Mortgage Loan, Mortgage Loan, Personal Loan,  Home Equity Loan',
 'Student Loan, Student Loan, Mortgage Loan, Payday Loan, Home Equity Loan, Mortgage Loan, Credit-Builder Loan,  Student Loan',
 'Personal Loan, Personal Loan, Auto Loan, Debt Consolidation Loan, Mortgage Loan, Auto Loan,  Personal Loan',
 'Home Equity Loan, Auto Loan, Personal Loan, Personal Loan, Mortgage Loan, Auto Loan, Debt Consolidation Loan,  Personal Loan',
 'Student Loan, Credit-Builder Loan,  Credit-Builder Loan',
 'Auto Loan, Credit-Builder Loan, Home Equity Loan, Debt Consolidation Loan, Mortgage Loan, Home Equity Loan, Auto Loan,  Not Specified',
 'Personal Loan, Mortgage Loan, Student Loan, Personal Loan, Debt Consolidation Loan, Mortgage Loan,  Debt Consolidation Loan',
 'Home Equity Loan, Student Loan,  Credit-Builder Loan',
 'Auto Loan, Debt Consolidation Loan, Debt Consolidation Loan, Credit-Builder Loan, Credit-Builder Loan,  Home Equity Loan',
 'Not Specified, Not Specified, Home Equity Loan,  Student Loan',
 'Personal Loan, Credit-Builder Loan, Not Specified,  Debt Consolidation Loan',
 'Debt Consolidation Loan, Payday Loan, Credit-Builder Loan, Auto Loan, Credit-Builder Loan, Home Equity Loan, Credit-Builder Loan, Payday Loan,  Mortgage Loan',
 'Payday Loan, Debt Consolidation Loan,  Not Specified',
 'Student Loan, Not Specified, Student Loan, Debt Consolidation Loan, Debt Consolidation Loan, Home Equity Loan, Payday Loan, Mortgage Loan,  Not Specified',
 'Not Specified,  Not Specified',
 'Payday Loan, Student Loan, Auto Loan, Mortgage Loan, Auto Loan, Payday Loan, Mortgage Loan,  Payday Loan',
 'Not Specified, Payday Loan, Mortgage Loan, Credit-Builder Loan, Personal Loan, Payday Loan, Debt Consolidation Loan,  Payday Loan',
 'Mortgage Loan, Student Loan, Credit-Builder Loan, Payday Loan, Credit-Builder Loan, Personal Loan,  Home Equity Loan',
 'Payday Loan, Home Equity Loan, Mortgage Loan, Debt Consolidation Loan,  Personal Loan',
 'Student Loan,  Home Equity Loan',
 'Mortgage Loan, Debt Consolidation Loan, Debt Consolidation Loan, Credit-Builder Loan,  Not Specified',
 'Credit-Builder Loan, Personal Loan,  Home Equity Loan',
 'Credit-Builder Loan,  Credit-Builder Loan',
 'Student Loan, Auto Loan,  Payday Loan',

In [28]:
unique_loans = long_data['Type_of_Loan'].str.split(',').explode().str.strip().unique().tolist()

In [29]:
unique_loans

['Auto Loan',
 'Credit-Builder Loan',
 'Personal Loan',
 'Home Equity Loan',
 'Not Specified',
 nan,
 'Mortgage Loan',
 'Student Loan',
 'Debt Consolidation Loan',
 'Payday Loan']

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Add any other comma-separated text columns here
# tfidf_cols = ['Type_of_Loan']

tfidf_dfs = []

# for col in tfidf_cols:
docs = (
    long_data['Type_of_Loan']
    .fillna('')
    .astype(str)
    .str.split(',')
    .apply(lambda items: ' '.join(
        item.strip().lower().replace(' ', '_')
        for item in items if item.strip()
    ))
)

In [31]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(docs)
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=[f"loan_type__{feat}" for feat in vectorizer.get_feature_names_out()],
    index=long_data.index
)
tfidf_dfs.append(tfidf_df)

In [32]:
# long_data = long_data.drop(columns=tfidf_cols)
new_data = pd.concat([long_data] + tfidf_dfs, axis=1)
new_data.shape

(100000, 35)

In [33]:
new_data.head()

,Customer_ID,Month,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,...,loan_type__auto_loan,loan_type__builder_loan,loan_type__credit,loan_type__debt_consolidation_loan,loan_type__home_equity_loan,loan_type__mortgage_loan,loan_type__not_specified,loan_type__payday_loan,loan_type__personal_loan,loan_type__student_loan
0,CUS_0xd40,January,23,Scientist,19114.12,1824.843333,3,4,3,4,...,0.45216,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0
1,CUS_0xd40,February,23,Scientist,19114.12,NaN,3,4,3,4,...,0.45216,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0
2,CUS_0xd40,March,-500,Scientist,19114.12,NaN,3,4,3,4,...,0.45216,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0
3,CUS_0xd40,April,23,Scientist,19114.12,NaN,3,4,3,4,...,0.45216,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0
4,CUS_0xd40,May,23,Scientist,19114.12,1824.843333,3,4,3,4,...,0.45216,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0

In [34]:
cat_cols

Index(['Customer_ID', 'Month', 'Occupation', 'Type_of_Loan', 'Credit_Mix',
       'Payment_of_Min_Amount', 'Payment_Behaviour', 'Credit_Score'],
      dtype='object')

In [35]:
long_data['Occupation'].unique()

array(['Scientist', '_______', 'Teacher', 'Engineer', 'Entrepreneur',
       'Developer', 'Lawyer', 'Media_Manager', 'Doctor', 'Journalist',
       'Manager', 'Accountant', 'Musician', 'Mechanic', 'Writer',
       'Architect'], dtype=object)

In [36]:
new_data = new_data.drop(columns = ['Type_of_Loan'])

In [37]:
cat_cols_new = new_data.select_dtypes(include = ['object', 'string']).columns.tolist()
cat_cols_new

['Customer_ID',
 'Month',
 'Occupation',
 'Credit_Mix',
 'Payment_of_Min_Amount',
 'Payment_Behaviour',
 'Credit_Score']

In [38]:
cat_cols_new.remove('Customer_ID')

In [39]:
cat_columns = [col for col in cat_cols_new if col != 'Target']
cat_columns

['Month',
 'Occupation',
 'Credit_Mix',
 'Payment_of_Min_Amount',
 'Payment_Behaviour',
 'Credit_Score']

In [40]:
# new_data['Credit_History_Age'].unique()

One-hot encoding categorical columns

In [41]:
new_data['mix_target'] = new_data['Credit_Score'] + new_data['Credit_Mix']
new_data['mix_target'].unique()

array(['Good_', 'GoodGood', 'StandardGood', 'Standard_',
       'StandardStandard', 'PoorStandard', 'Poor_', 'GoodStandard',
       'PoorBad', 'StandardBad', 'GoodBad', 'PoorGood'], dtype=object)

In [42]:
new_data['mix_target'].value_counts()

mix_target
StandardStandard    26577
GoodGood            11875
PoorBad             11409
Standard_           10704
StandardGood         8601
PoorStandard         7859
StandardBad          7292
Poor_                5869
PoorGood             3861
Good_                3622
GoodStandard         2043
GoodBad               288
Name: count, dtype: int64

In [43]:
new_data['Credit_Score'].value_counts()

Credit_Score
Standard    53174
Poor        28998
Good        17828
Name: count, dtype: int64

the credit mix statuses can be very different from the actual credit standing of the customer

In [44]:
new_data.head()

,Customer_ID,Month,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,...,loan_type__builder_loan,loan_type__credit,loan_type__debt_consolidation_loan,loan_type__home_equity_loan,loan_type__mortgage_loan,loan_type__not_specified,loan_type__payday_loan,loan_type__personal_loan,loan_type__student_loan,mix_target
0,CUS_0xd40,January,23,Scientist,19114.12,1824.843333,3,4,3,4,...,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0,Good_
1,CUS_0xd40,February,23,Scientist,19114.12,NaN,3,4,3,4,...,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0,GoodGood
2,CUS_0xd40,March,-500,Scientist,19114.12,NaN,3,4,3,4,...,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0,GoodGood
3,CUS_0xd40,April,23,Scientist,19114.12,NaN,3,4,3,4,...,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0,GoodGood
4,CUS_0xd40,May,23,Scientist,19114.12,1824.843333,3,4,3,4,...,0.4444,0.4444,0.0,0.44655,0.0,0.0,0.0,0.44851,0.0,GoodGood

In [45]:
data = new_data.copy()

In [46]:
data['Month'] = pd.to_datetime(new_data['Month'], format='%B').dt.month
# data.head()
data['order'] = data.sort_values(by='Month', ascending= False).groupby('Customer_ID').cumcount() + 1
# data[['Customer_ID', 'Month', 'order']].head(20)
# records  = data[data['order'] <= 3]
# records.head()

In [47]:
features = data.groupby('Customer_ID').agg(
    max_delayed_payment = ('Num_of_Delayed_Payment', 'max'),
    max_credit_util = ('Credit_Utilization_Ratio', 'max'),
    credit_util_var = ('Credit_Utilization_Ratio', 'var')
).reset_index()
features.head()

  Customer_ID  max_delayed_payment  max_credit_util  credit_util_var
0  CUS_0x1000                 28.0        40.082272        23.612754
1  CUS_0x1009               1749.0        40.286997        28.889929
2  CUS_0x100b                  9.0        43.829630        30.524752
3  CUS_0x1011                 17.0        29.198639         1.677459
4  CUS_0x1013                  9.0        41.920614        42.617492

In [48]:
month1 = data[data['order'] == 1].rename(
    columns= {'Month': 'latest_month', 'Credit_Score': 'Target'})
# month1.head()
month2 = data[data['order'] == 2][['Customer_ID', 'Monthly_Balance', 'Credit_Utilization_Ratio', 'Num_of_Delayed_Payment', 'Delay_from_due_date']].rename(
    columns= {'Monthly_Balance': 'month2_balance', 'Credit_Utilization_Ratio': 'month2_credit_util', 'Num_of_Delayed_Payment': 'month2_delayed_payment', 'Delay_from_due_date': 'month2_delay_from_due_date'})
month3 = data[data['order'] == 3][['Customer_ID', 'Monthly_Balance', 'Credit_Utilization_Ratio', 'Num_of_Delayed_Payment', 'Delay_from_due_date']].rename(
    columns= {'Monthly_Balance': 'month3_balance', 'Credit_Utilization_Ratio': 'month3_credit_util', 'Num_of_Delayed_Payment': 'month3_delayed_payment', 'Delay_from_due_date': 'month3_delay_from_due_date'})
user_history = month1.merge(month2, on= 'Customer_ID', how = 'left').merge(
    month3 , on = 'Customer_ID', how = 'left'
    ).merge(features, on = 'Customer_ID', how = 'left')
user_history.head()

,Customer_ID,latest_month,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,...,month2_credit_util,month2_delayed_payment,month2_delay_from_due_date,month3_balance,month3_credit_util,month3_delayed_payment,month3_delay_from_due_date,max_delayed_payment,max_credit_util,credit_util_var
0,CUS_0xd40,8,23,Scientist,19114.12,1824.843333,3,4,3,4,...,22.537593,8.0,3,340.479212,27.262259,4.0,8,8.0,31.944960,11.466897
1,CUS_0x21b1,8,28,Teacher,34847.84,3037.986667,2,4,6,1,...,31.131702,4.0,3,481.505262,33.381010,0.0,3,4.0,39.182656,21.093257
2,CUS_0x2dbc,8,34,Engineer,143162.64,12187.220000,1,5,8,3,...,38.068624,6.0,8,963.921581,39.783993,6.0,8,8.0,41.702573,33.246935
3,CUS_0xb891,8,55,Entrepreneur,30689.89,2612.490833,2,5,4,-100,...,26.056395,NaN,5,419.880784,27.445422,6.0,5,9.0,41.154317,34.213323
4,CUS_0x1cdb,8,21,Developer,35547.71,2853.309167,7,5,5,-100,...,26.263823,15.0,10,497.687279,29.217556,15.0,5,17.0,41.776187,45.494381

In [49]:
user_history['Num_of_Loan'] = user_history['Num_of_Loan'].abs()

In [50]:
user_history['Num_of_Loan'].min()

np.int64(0)

In [51]:
user_history['balance_m1_m2'] = (user_history['Monthly_Balance'] - user_history['month2_balance']) / user_history['month2_balance']
user_history['balance_m2_m3'] = (user_history['month2_balance'] - user_history['month3_balance']) / user_history['month3_balance']

In [52]:
model_data = user_history.drop(columns = ['Customer_ID', 'order', 'mix_target', 'latest_month'])

In [53]:
cat_features = model_data.select_dtypes(include = ['object', 'string']).columns.tolist()
cat_features

['Occupation',
 'Credit_Mix',
 'Payment_of_Min_Amount',
 'Payment_Behaviour',
 'Target']

In [54]:
cat_features.remove('Target')

In [55]:
for col in cat_features:
    model_data[col] = model_data[col].astype('category')
target_map = {'Poor': 0, 'Standard': 1, 'Good': 2}
model_data['Target'] = model_data['Target'].map(target_map)

## LGBM Credit Classification Model

In [56]:
X = model_data.drop(columns = ['Target'])
y = model_data['Target']
X_train, X_test , y_train , y_test = train_test_split(X,y, test_size = 0.25, 
                                                      random_state=42, stratify = y)

In [57]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# y_train should be your training labels
classes = np.unique(y_train)
class_weights = compute_class_weight('balanced', classes=classes, y=y_train)
class_weight_dict = dict(zip(classes, class_weights))

# For LightGBM
# lgbm = LGBMClassifier(class_weight=class_weight_dict, ...)

In [58]:
from sklearn.utils.class_weight import compute_sample_weight

sample_weights = compute_sample_weight(class_weight='balanced', y=y_train)

train_set = lgb.Dataset(X_train, label=y_train, weight=sample_weights,
                        categorical_feature=cat_features)
test_set = lgb.Dataset(X_test, label=y_test, reference=train_set,
                       categorical_feature=cat_features)

In [59]:
train_set = lgb.Dataset(X_train, label=y_train, categorical_feature=cat_features)
val_set = lgb.Dataset(X_test, label=y_test, reference = train_set)

In [60]:
params = {
    'objective':        'multiclass',
    'num_class':        3,
    'metric':           'multi_logloss',
    'num_leaves':       63,
    'learning_rate':    0.05,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.8,
    'bagging_freq':     5,
    'verbose':          -1,
    'is_unbalance':     True
    # 'class_weight':     class_weight_dict
}

In [61]:
model = lgb.train(
    params,
    train_set,
    num_boost_round=500,
    valid_sets=[val_set],
    # callbacks=[lgb.early_stopping(50), lgb.log_evaluation(50)],
)

In [62]:
model.feature_importance(importance_type='gain')

array([ 3543.3913901 ,  4332.26770306,  3577.98831941,  6007.33018756,
        2711.71767171,  3794.73020206,  8580.18496111,  1565.03979905,
        3215.26248213,  3814.44216075,  8085.8062278 ,  3995.38805661,
        6187.7066435 , 14816.65747655,  4743.07059454,  5551.77976115,
        2558.23592891,  6199.65836079,  7255.28701715,  1682.12512301,
        4733.03083069,  1667.31808302,  1532.76231062,   339.08160965,
        1877.37617405,  1767.21922392,  1871.40455845,  1574.01489466,
        1827.95271818,  1696.34921134,  1871.90557468,  4664.20433006,
        5176.86132538,  3569.10016407,  3132.4180097 ,  4921.77992545,
        5036.1674239 ,  3781.11154167,  3994.72206452,  2282.57555325,
        4392.74538956,  4910.12365101,  5535.40352486,  5214.77607342])

In [63]:
from sklearn.metrics import cohen_kappa_score, classification_report, confusion_matrix, roc_auc_score
import xgboost as xgb
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import cohen_kappa_score, roc_auc_score
import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

/Users/josephineamponsah/Documents/credit-scoring-nlp-dl/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [64]:
import optuna
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score

In [65]:
from lightgbm import LGBMClassifier

In [66]:
## Cross validation
def lgb_objective(trial, X_train, X_val , y_train , y_val):
    params = {
        'objective':           'multiclass',
        'num_class':           3,
        'metric':              'multi_logloss',
        'n_estimators':        1000,
        # 'early_stopping_rounds': 50,
        'random_state':        42,
        # 'verbose':             -1,
        'learning_rate':       trial.suggest_float('learning_rate', 0.01, 0.15, log=True),
        'num_leaves':          trial.suggest_int('num_leaves', 10, 200),
        'max_depth':           trial.suggest_int('max_depth', 3, 10),
        'subsample':           trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree':    trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_samples':   trial.suggest_int('min_child_samples', 10, 100),
        'reg_alpha':           trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'cat_l2': trial.suggest_float('cat_l2', 1, 30),
        'cat_smooth': trial.suggest_float('cat_smooth', 1, 50),
        'reg_lambda':          trial.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
    }
    model = LGBMClassifier(**params, class_weight=class_weight_dict)
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        categorical_feature=cat_features,
        eval_metric='multi_logloss',
        # early_stopping_rounds=30,
        # verbose=False
    )
    
    preds = model.predict(X_val)
    return accuracy_score(y_val, preds)

study = optuna.create_study(direction='maximize')
study.optimize(lambda trial: lgb_objective(trial, X_train, X_test, y_train, y_test), n_trials=30)

print("Best params:", study.best_params)

Best params: {'learning_rate': 0.029043168600341025, 'num_leaves': 143, 'max_depth': 8, 'subsample': 0.9470923311119088, 'colsample_bytree': 0.9554669633041123, 'min_child_samples': 84, 'reg_alpha': 0.13802857293602833, 'cat_l2': 12.59920093356147, 'cat_smooth': 12.878567377973717, 'reg_lambda': 0.03281645129230756}

In [67]:
opt_lgb_model = lgb.LGBMClassifier(**study.best_params)
opt_lgb_model.fit(X_train, y_train, eval_set=[(X_test, y_test)], categorical_feature=cat_features, eval_metric='multi_logloss')

LGBMClassifier(cat_l2=12.59920093356147, cat_smooth=12.878567377973717,
               colsample_bytree=0.9554669633041123,
               learning_rate=0.029043168600341025, max_depth=8,
               min_child_samples=84, num_leaves=143,
               reg_alpha=0.13802857293602833, reg_lambda=0.03281645129230756,
               subsample=0.9470923311119088)

### LGBM Evaluation

In [68]:
# lgb_study = optuna.create_study(direction='maximize')
# lgb_study.optimize(lambda trial: lgb_objective(trial, X, y), n_trials=50)
y_prob = opt_lgb_model.predict_proba(X_test)   # shape (n_samples, 3) — then argmax makes sense
y_pred = opt_lgb_model.predict(X_test)          # shape (n_samples,) — class labels directly


qwk = cohen_kappa_score(y_test, y_pred, weights='quadratic')
print(f"QWK: {qwk:.4f}")
print(classification_report(y_test, y_pred, target_names=['Poor', 'Standard', 'Good']))
print(confusion_matrix(y_test, y_pred))

# print(f"Best LGB | QWK: {lgb_study.best_value:.4f} | Params: {lgb_study.best_params}")

QWK: 0.5043
              precision    recall  f1-score   support

        Poor       0.64      0.55      0.59       901
    Standard       0.63      0.75      0.68      1621
        Good       0.58      0.40      0.47       603

    accuracy                           0.62      3125
   macro avg       0.62      0.57      0.58      3125
weighted avg       0.62      0.62      0.62      3125

[[ 496  374   31]
 [ 264 1212  145]
 [  10  353  240]]

In [69]:
auc = roc_auc_score(y_test, y_prob, multi_class='ovr')
print(f"AUC: {auc:.4f}")

AUC: 0.7822

In [70]:
from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score
from imblearn.pipeline import Pipeline
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler
# import optuna
# import numpy as np

def lgb_objective(trial, X, y):
    params = {
        'objective': 'multiclass',
        'num_class': 3,
        'metric': 'multi_logloss',
        'n_estimators': 1000,
        'random_state': 42,
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.15, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 10, 200),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_samples': trial.suggest_int('min_child_samples', 10, 100),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'cat_l2': trial.suggest_float('cat_l2', 1, 30),
        'cat_smooth': trial.suggest_float('cat_smooth', 1, 50),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
    }

    # Example target size strategy:
    # - cap majority classes by undersampling
    # - raise minority classes by oversampling
    under = RandomUnderSampler(
        sampling_strategy={
            0: 500,   # class 0 down to 1500
            1: 500,   # class 1 down to 1500
            2: 300    # keep / downsample class 2 if needed
        },
        random_state=42
    )

    over = RandomOverSampler(
        sampling_strategy={
            2: 500    # oversample minority class 2 up to 500
        },
        random_state=42
    )

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for train_idx, val_idx in cv.split(X, y):
        X_train_fold = X.iloc[train_idx] if hasattr(X, "iloc") else X[train_idx]
        X_val_fold = X.iloc[val_idx] if hasattr(X, "iloc") else X[val_idx]
        y_train_fold = y.iloc[train_idx] if hasattr(y, "iloc") else y[train_idx]
        y_val_fold = y.iloc[val_idx] if hasattr(y, "iloc") else y[val_idx]

        # Resample ONLY training fold
        X_res, y_res = under.fit_resample(X_train_fold, y_train_fold)
        X_res, y_res = over.fit_resample(X_res, y_res)

        model = LGBMClassifier(**params)

        model.fit(
            X_res,
            y_res,
            eval_set=[(X_val_fold, y_val_fold)],
            categorical_feature=cat_features,
            eval_metric='multi_logloss'
        )

        preds = model.predict(X_val_fold)
        scores.append(accuracy_score(y_val_fold, preds))

    return np.mean(scores)

study = optuna.create_study(direction='maximize')
study.optimize(lambda trial: lgb_objective(trial, X_train, y_train), n_trials=30)

print("Best params:", study.best_params)

Best params: {'learning_rate': 0.033457606596029504, 'num_leaves': 181, 'max_depth': 10, 'subsample': 0.9943690510825496, 'colsample_bytree': 0.566487510381879, 'min_child_samples': 10, 'reg_alpha': 1.4374220740823367, 'cat_l2': 26.472361615480125, 'cat_smooth': 47.12483450847602, 'reg_lambda': 0.17745071225387926}

In [71]:
optsample_lgb_model = lgb.LGBMClassifier(**study.best_params)
optsample_lgb_model.fit(X_train, y_train, eval_set=[(X_test, y_test)], categorical_feature=cat_features, eval_metric='multi_logloss')

# lgb_study = optuna.create_study(direction='maximize')
# lgb_study.optimize(lambda trial: lgb_objective(trial, X, y), n_trials=50)
y_prob = optsample_lgb_model.predict_proba(X_test)   # shape (n_samples, 3) — then argmax makes sense
y_pred = optsample_lgb_model.predict(X_test)          # shape (n_samples,) — class labels directly


qwk = cohen_kappa_score(y_test, y_pred, weights='quadratic')
print(f"QWK: {qwk:.4f}")
print(classification_report(y_test, y_pred, target_names=['Poor', 'Standard', 'Good']))
print(confusion_matrix(y_test, y_pred))

# print(f"Best LGB | QWK: {lgb_study.best_value:.4f} | Params: {lgb_study.best_params}")

auc = roc_auc_score(y_test, y_prob, multi_class='ovr')
print(f"AUC: {auc:.4f}")

QWK: 0.5124
              precision    recall  f1-score   support

        Poor       0.65      0.56      0.60       901
    Standard       0.63      0.75      0.68      1621
        Good       0.57      0.41      0.48       603

    accuracy                           0.63      3125
   macro avg       0.62      0.57      0.59      3125
weighted avg       0.62      0.63      0.62      3125

[[ 505  365   31]
 [ 261 1209  151]
 [  10  347  246]]
AUC: 0.7824

## XGBoost Model

In [72]:
from xgboost import XGBClassifier

In [78]:
## Cross validation
def xgb_objective(trial, X_train, X_val , y_train , y_val):
    xgb_params = {
        'max_cat_to_onehot': 7,
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'max_cat_threshold': trial.suggest_int('max_cat_threshold', 1, 64),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.15, log=True),
        'min_child_weight': trial.suggest_float('min_child_weight', 1e-4, 10.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-4, 10.0, log=True),
        'tree_method': trial.suggest_categorical('tree_method', [ 'hist']),
        'max_leaves': trial.suggest_int('max_leaves', 10, 200),
        'max_bin': trial.suggest_int('max_bin', 256, 1024),
        
    }
    sample_weights = y_train.map(class_weight_dict)
    model = XGBClassifier(**xgb_params, enable_categorical = True,
        eval_metric = 'mlogloss')
    model.fit(
        X_train, y_train,
        sample_weight=sample_weights,
        eval_set=[(X_val, y_val)],
        # early_stopping_rounds=30,
        # verbose=False
    )
    
    preds = model.predict(X_val)
    return accuracy_score(y_val, preds)

study = optuna.create_study(direction='maximize')
study.optimize(lambda trial: xgb_objective(trial, X_train, X_test, y_train, y_test), n_trials=30)

print("Best params:", study.best_params)

[0]	validation_0-mlogloss:1.07187
[1]	validation_0-mlogloss:1.04932
[2]	validation_0-mlogloss:1.03016
[3]	validation_0-mlogloss:1.01231
[4]	validation_0-mlogloss:0.99731
[5]	validation_0-mlogloss:0.98342
[6]	validation_0-mlogloss:0.97151
[7]	validation_0-mlogloss:0.96140
[8]	validation_0-mlogloss:0.95252
[9]	validation_0-mlogloss:0.94381
[10]	validation_0-mlogloss:0.93543
[11]	validation_0-mlogloss:0.92819
[12]	validation_0-mlogloss:0.92238
[13]	validation_0-mlogloss:0.91653
[14]	validation_0-mlogloss:0.91140
[15]	validation_0-mlogloss:0.90668
[16]	validation_0-mlogloss:0.90255
[17]	validation_0-mlogloss:0.89893
[18]	validation_0-mlogloss:0.89460
[19]	validation_0-mlogloss:0.89041
[20]	validation_0-mlogloss:0.88731
[21]	validation_0-mlogloss:0.88441
[22]	validation_0-mlogloss:0.88154
[23]	validation_0-mlogloss:0.87838
[24]	validation_0-mlogloss:0.87575
[25]	validation_0-mlogloss:0.87376
[26]	validation_0-mlogloss:0.87188
[27]	validation_0-mlogloss:0.87006
[28]	validation_0-mlogloss:0.86845
[29]	validation_0-mlogloss:0.86630
[30]	validation_0-mlogloss:0.86527
[31]	validation_0-mlogloss:0.86401
[32]	validation_0-mlogloss:0.86275
[33]	validation_0-mlogloss:0.86191
[34]	validation_0-mlogloss:0.86041
[35]	validation_0-mlogloss:0.85972
[36]	validation_0-mlogloss:0.85853
[37]	validation_0-mlogloss:0.85728
[38]	validation_0-mlogloss:0.85633
[39]	validation_0-mlogloss:0.85553
[40]	validation_0-mlogloss:0.85478
[41]	validation_0-mlogloss:0.85366
[42]	validation_0-mlogloss:0.85275
[43]	validation_0-mlogloss:0.85176
[44]	validation_0-mlogloss:0.85096
[45]	validation_0-mlogloss:0.85026
[46]	validation_0-mlogloss:0.84962
[47]	validation_0-mlogloss:0.84879
[48]	validation_0-mlogloss:0.84827
[49]	validation_0-mlogloss:0.84779
[50]	validation_0-mlogloss:0.84739
[51]	validation_0-mlogloss:0.84683
[52]	validation_0-mlogloss:0.84632
[53]	validation_0-mlogloss:0.84581
[54]	validation_0-mlogloss:0.84504
[55]	validation_0-mlogloss:0.84453
[56]	validation_0-mlogloss:0.84434
[57]	validation_0-mlogloss:0.84421
[58]	validation_0-mlogloss:0.84386
[59]	validation_0-mlogloss:0.84309
[60]	validation_0-mlogloss:0.84291
[61]	validation_0-mlogloss:0.84234
[62]	validation_0-mlogloss:0.84198
[63]	validation_0-mlogloss:0.84154
[64]	validation_0-mlogloss:0.84112
[65]	validation_0-mlogloss:0.84055
[66]	validation_0-mlogloss:0.83973
[67]	validation_0-mlogloss:0.83941
[68]	validation_0-mlogloss:0.83886
[69]	validation_0-mlogloss:0.83871
[70]	validation_0-mlogloss:0.83849
[71]	validation_0-mlogloss:0.83834
[72]	validation_0-mlogloss:0.83794
[73]	validation_0-mlogloss:0.83767
[74]	validation_0-mlogloss:0.83725
[75]	validation_0-mlogloss:0.83712
[76]	validation_0-mlogloss:0.83667
[77]	validation_0-mlogloss:0.83646
[78]	validation_0-mlogloss:0.83651
[79]	validation_0-mlogloss:0.83618
[80]	validation_0-mlogloss:0.83602
[81]	validation_0-mlogloss:0.83581
[82]	validation_0-mlogloss:0.83550
[83]	validation_0-mlogloss:0.83534
[84]	validation_0-mlogloss:0.83512
[85]	validation_0-mlogloss:0.83506
[86]	validation_0-mlogloss:0.83494
[87]	validation_0-mlogloss:0.83459
[88]	validation_0-mlogloss:0.83487
[89]	validation_0-mlogloss:0.83455
[90]	validation_0-mlogloss:0.83450
[91]	validation_0-mlogloss:0.83438
[92]	validation_0-mlogloss:0.83447
[93]	validation_0-mlogloss:0.83450
[94]	validation_0-mlogloss:0.83411
[95]	validation_0-mlogloss:0.83381
[96]	validation_0-mlogloss:0.83362
[97]	validation_0-mlogloss:0.83396
[98]	validation_0-mlogloss:0.83372
[99]	validation_0-mlogloss:0.83357
[0]	validation_0-mlogloss:1.09259
[1]	validation_0-mlogloss:1.08679
[2]	validation_0-mlogloss:1.08123
[3]	validation_0-mlogloss:1.07580
[4]	validation_0-mlogloss:1.07064
[5]	validation_0-mlogloss:1.06544
[6]	validation_0-mlogloss:1.06043
[7]	validation_0-mlogloss:1.05563
[8]	validation_0-mlogloss:1.05094
[9]	validation_0-mlogloss:1.04642
[10]	validation_0-mlogloss:1.04206
[11]	validation_0-mlogloss:1.03783
[12]	validation_0-mlogloss:1.03377
[13]	validation_0-mlogloss:1.02981
[14]	validation_0-mlogloss:1.02597
[15]	validation_0-mlogloss:1.02233
[16]	validation_0-mlogloss:1.01872
[17]	validation_0-mlogloss:1.01524
[18]	validation_0-mlogloss:1.01182
[19]	validation_0-mlogloss:1.00857
[20]	validation_0-mlogloss:1.00537
[21]	validation_0-mlogloss:1.00226
[22]	validation_0-mlogloss:0.99930
[23]	validation_0-mlogloss:0.99638
[24]	validation_0-mlogloss:0.99358
[25]	validation_0-mlogloss:0.99077
[26]	validation_0-mlogloss:0.98814
[27]	validation_0-mlogloss:0.98556
[28]	validation_0-mlogloss:0.98307
[29]	validation_0-mlogloss:0.98057
[30]	validation_0-mlogloss:0.97823
[31]	validation_0-mlogloss:0.97583
[32]	validation_0-mlogloss:0.97363
[33]	validation_0-mlogloss:0.97146
[34]	validation_0-mlogloss:0.96941
[35]	validation_0-mlogloss:0.96731
[36]	validation_0-mlogloss:0.96528
[37]	validation_0-mlogloss:0.96334
[38]	validation_0-mlogloss:0.96154
[39]	validation_0-mlogloss:0.95970
[40]	validation_0-mlogloss:0.95786
[41]	validation_0-mlogloss:0.95622
[42]	validation_0-mlogloss:0.95459
[43]	validation_0-mlogloss:0.95292
[44]	validation_0-mlogloss:0.95138
[45]	validation_0-mlogloss:0.94980
[46]	validation_0-mlogloss:0.94821
[47]	validation_0-mlogloss:0.94675
[48]	validation_0-mlogloss:0.94516
[49]	validation_0-mlogloss:0.94363
[50]	validation_0-mlogloss:0.94212
[51]	validation_0-mlogloss:0.94063
[52]	validation_0-mlogloss:0.93923
[53]	validation_0-mlogloss:0.93791
[54]	validation_0-mlogloss:0.93663
[55]	validation_0-mlogloss:0.93534
[56]	validation_0-mlogloss:0.93419
[57]	validation_0-mlogloss:0.93300
[58]	validation_0-mlogloss:0.93185
[59]	validation_0-mlogloss:0.93072
[60]	validation_0-mlogloss:0.92966
[61]	validation_0-mlogloss:0.92853
[62]	validation_0-mlogloss:0.92754
[63]	validation_0-mlogloss:0.92656
[64]	validation_0-mlogloss:0.92560
[65]	validation_0-mlogloss:0.92474
[66]	validation_0-mlogloss:0.92390
[67]	validation_0-mlogloss:0.92309
[68]	validation_0-mlogloss:0.92224
[69]	validation_0-mlogloss:0.92141
[70]	validation_0-mlogloss:0.92059
[71]	validation_0-mlogloss:0.91982
[72]	validation_0-mlogloss:0.91906
[73]	validation_0-mlogloss:0.91828
[74]	validation_0-mlogloss:0.91746
[75]	validation_0-mlogloss:0.91675
[76]	validation_0-mlogloss:0.91599
[77]	validation_0-mlogloss:0.91523
[78]	validation_0-mlogloss:0.91450
[79]	validation_0-mlogloss:0.91376
[80]	validation_0-mlogloss:0.91308
[81]	validation_0-mlogloss:0.91238
[82]	validation_0-mlogloss:0.91171
[83]	validation_0-mlogloss:0.91106
[84]	validation_0-mlogloss:0.91044
[85]	validation_0-mlogloss:0.90976
[86]	validation_0-mlogloss:0.90909
[87]	validation_0-mlogloss:0.90844
[88]	validation_0-mlogloss:0.90786
[89]	validation_0-mlogloss:0.90728
[90]	validation_0-mlogloss:0.90674
[91]	validation_0-mlogloss:0.90623
[92]	validation_0-mlogloss:0.90572
[93]	validation_0-mlogloss:0.90522
[94]	validation_0-mlogloss:0.90472
[95]	validation_0-mlogloss:0.90424
[96]	validation_0-mlogloss:0.90378
[97]	validation_0-mlogloss:0.90331
[98]	validation_0-mlogloss:0.90287
[99]	validation_0-mlogloss:0.90242
[0]	validation_0-mlogloss:1.09469
[1]	validation_0-mlogloss:1.09085
[2]	validation_0-mlogloss:1.08711
[3]	validation_0-mlogloss:1.08346
[4]	validation_0-mlogloss:1.07986
[5]	validation_0-mlogloss:1.07633
[6]	validation_0-mlogloss:1.07288
[7]	validation_0-mlogloss:1.06951
[8]	validation_0-mlogloss:1.06619
[9]	validation_0-mlogloss:1.06298
[10]	validation_0-mlogloss:1.05979
[11]	validation_0-mlogloss:1.05668
[12]	validation_0-mlogloss:1.05366
[13]	validation_0-mlogloss:1.05068
[14]	validation_0-mlogloss:1.04777
[15]	validation_0-mlogloss:1.04488
[16]	validation_0-mlogloss:1.04209
[17]	validation_0-mlogloss:1.03933
[18]	validation_0-mlogloss:1.03663
[19]	validation_0-mlogloss:1.03395
[20]	validation_0-mlogloss:1.03132
[21]	validation_0-mlogloss:1.02876
[22]	validation_0-mlogloss:1.02629
[23]	validation_0-mlogloss:1.02386
[24]	validation_0-mlogloss:1.02146
[25]	validation_0-mlogloss:1.01914
[26]	validation_0-mlogloss:1.01671
[27]	validation_0-mlogloss:1.01441
[28]	validation_0-mlogloss:1.01208
[29]	validation_0-mlogloss:1.00981
[30]	validation_0-mlogloss:1.00757
[31]	validation_0-mlogloss:1.00539
[32]	validation_0-mlogloss:1.00321
[33]	validation_0-mlogloss:1.00114
[34]	validation_0-mlogloss:0.99916
[35]	validation_0-mlogloss:0.99724
[36]	validation_0-mlogloss:0.99534
[37]	validation_0-mlogloss:0.99345
[38]	validation_0-mlogloss:0.99165
[39]	validation_0-mlogloss:0.98977
[40]	validation_0-mlogloss:0.98803
[41]	validation_0-mlogloss:0.98631
[42]	validation_0-mlogloss:0.98459
[43]	validation_0-mlogloss:0.98296
[44]	validation_0-mlogloss:0.98129
[45]	validation_0-mlogloss:0.97967
[46]	validation_0-mlogloss:0.97811
[47]	validation_0-mlogloss:0.97653
[48]	validation_0-mlogloss:0.97496
[49]	validation_0-mlogloss:0.97344
[50]	validation_0-mlogloss:0.97186
[51]	validation_0-mlogloss:0.97042
[52]	validation_0-mlogloss:0.96898
[53]	validation_0-mlogloss:0.96758
[54]	validation_0-mlogloss:0.96617
[55]	validation_0-mlogloss:0.96477
[56]	validation_0-mlogloss:0.96339
[57]	validation_0-mlogloss:0.96209
[58]	validation_0-mlogloss:0.96074
[59]	validation_0-mlogloss:0.95950
[60]	validation_0-mlogloss:0.95814
[61]	validation_0-mlogloss:0.95695
[62]	validation_0-mlogloss:0.95573
[63]	validation_0-mlogloss:0.95452
[64]	validation_0-mlogloss:0.95329
[65]	validation_0-mlogloss:0.95208
[66]	validation_0-mlogloss:0.95095
[67]	validation_0-mlogloss:0.94981
[68]	validation_0-mlogloss:0.94873
[69]	validation_0-mlogloss:0.94759
[70]	validation_0-mlogloss:0.94650
[71]	validation_0-mlogloss:0.94538
[72]	validation_0-mlogloss:0.94432
[73]	validation_0-mlogloss:0.94320
[74]	validation_0-mlogloss:0.94216
[75]	validation_0-mlogloss:0.94114
[76]	validation_0-mlogloss:0.94012
[77]	validation_0-mlogloss:0.93911
[78]	validation_0-mlogloss:0.93809
[79]	validation_0-mlogloss:0.93712
[80]	validation_0-mlogloss:0.93616
[81]	validation_0-mlogloss:0.93521
[82]	validation_0-mlogloss:0.93433
[83]	validation_0-mlogloss:0.93335
[84]	validation_0-mlogloss:0.93246
[85]	validation_0-mlogloss:0.93160
[86]	validation_0-mlogloss:0.93073
[87]	validation_0-mlogloss:0.92996
[88]	validation_0-mlogloss:0.92916
[89]	validation_0-mlogloss:0.92834
[90]	validation_0-mlogloss:0.92758
[91]	validation_0-mlogloss:0.92689
[92]	validation_0-mlogloss:0.92610
[93]	validation_0-mlogloss:0.92536
[94]	validation_0-mlogloss:0.92462
[95]	validation_0-mlogloss:0.92384
[96]	validation_0-mlogloss:0.92317
[97]	validation_0-mlogloss:0.92235
[98]	validation_0-mlogloss:0.92155
[99]	validation_0-mlogloss:0.92078
[0]	validation_0-mlogloss:1.08376
[1]	validation_0-mlogloss:1.07034
[2]	validation_0-mlogloss:1.05788
[3]	validation_0-mlogloss:1.04654
[4]	validation_0-mlogloss:1.03597
[5]	validation_0-mlogloss:1.02619
[6]	validation_0-mlogloss:1.01715
[7]	validation_0-mlogloss:1.00844
[8]	validation_0-mlogloss:1.00024
[9]	validation_0-mlogloss:0.99273
[10]	validation_0-mlogloss:0.98612
[11]	validation_0-mlogloss:0.97985
[12]	validation_0-mlogloss:0.97404
[13]	validation_0-mlogloss:0.96853
[14]	validation_0-mlogloss:0.96314
[15]	validation_0-mlogloss:0.95817
[16]	validation_0-mlogloss:0.95327
[17]	validation_0-mlogloss:0.94888
[18]	validation_0-mlogloss:0.94430
[19]	validation_0-mlogloss:0.94023
[20]	validation_0-mlogloss:0.93658
[21]	validation_0-mlogloss:0.93301
[22]	validation_0-mlogloss:0.92953
[23]	validation_0-mlogloss:0.92601
[24]	validation_0-mlogloss:0.92313
[25]	validation_0-mlogloss:0.92028
[26]	validation_0-mlogloss:0.91758
[27]	validation_0-mlogloss:0.91478
[28]	validation_0-mlogloss:0.91197
[29]	validation_0-mlogloss:0.90948
[30]	validation_0-mlogloss:0.90723
[31]	validation_0-mlogloss:0.90520
[32]	validation_0-mlogloss:0.90302
[33]	validation_0-mlogloss:0.90096
[34]	validation_0-mlogloss:0.89894
[35]	validation_0-mlogloss:0.89696
[36]	validation_0-mlogloss:0.89529
[37]	validation_0-mlogloss:0.89363
[38]	validation_0-mlogloss:0.89227
[39]	validation_0-mlogloss:0.89054
[40]	validation_0-mlogloss:0.88947
[41]	validation_0-mlogloss:0.88775
[42]	validation_0-mlogloss:0.88617
[43]	validation_0-mlogloss:0.88468
[44]	validation_0-mlogloss:0.88351
[45]	validation_0-mlogloss:0.88222
[46]	validation_0-mlogloss:0.88112
[47]	validation_0-mlogloss:0.88021
[48]	validation_0-mlogloss:0.87919
[49]	validation_0-mlogloss:0.87835
[50]	validation_0-mlogloss:0.87728
[51]	validation_0-mlogloss:0.87642
[52]	validation_0-mlogloss:0.87538
[53]	validation_0-mlogloss:0.87483
[54]	validation_0-mlogloss:0.87378
[55]	validation_0-mlogloss:0.87298
[56]	validation_0-mlogloss:0.87197
[57]	validation_0-mlogloss:0.87118
[58]	validation_0-mlogloss:0.87046
[59]	validation_0-mlogloss:0.86963
[60]	validation_0-mlogloss:0.86915
[61]	validation_0-mlogloss:0.86845
[62]	validation_0-mlogloss:0.86768
[63]	validation_0-mlogloss:0.86704
[64]	validation_0-mlogloss:0.86647
[65]	validation_0-mlogloss:0.86588
[66]	validation_0-mlogloss:0.86538
[67]	validation_0-mlogloss:0.86467
[68]	validation_0-mlogloss:0.86398
[69]	validation_0-mlogloss:0.86330
[70]	validation_0-mlogloss:0.86252
[71]	validation_0-mlogloss:0.86207
[72]	validation_0-mlogloss:0.86145
[73]	validation_0-mlogloss:0.86081
[74]	validation_0-mlogloss:0.86040
[75]	validation_0-mlogloss:0.85966
[76]	validation_0-mlogloss:0.85905
[77]	validation_0-mlogloss:0.85869
[78]	validation_0-mlogloss:0.85818
[79]	validation_0-mlogloss:0.85768
[80]	validation_0-mlogloss:0.85720
[81]	validation_0-mlogloss:0.85667
[82]	validation_0-mlogloss:0.85609
[83]	validation_0-mlogloss:0.85557
[84]	validation_0-mlogloss:0.85527
[85]	validation_0-mlogloss:0.85476
[86]	validation_0-mlogloss:0.85445
[87]	validation_0-mlogloss:0.85416
[88]	validation_0-mlogloss:0.85395
[89]	validation_0-mlogloss:0.85345
[90]	validation_0-mlogloss:0.85303
[91]	validation_0-mlogloss:0.85254
[92]	validation_0-mlogloss:0.85230
[93]	validation_0-mlogloss:0.85187
[94]	validation_0-mlogloss:0.85150
[95]	validation_0-mlogloss:0.85120
[96]	validation_0-mlogloss:0.85087
[97]	validation_0-mlogloss:0.85067
[98]	validation_0-mlogloss:0.85043
[99]	validation_0-mlogloss:0.85029
[0]	validation_0-mlogloss:1.09097
[1]	validation_0-mlogloss:1.08366
[2]	validation_0-mlogloss:1.07674
[3]	validation_0-mlogloss:1.07010
[4]	validation_0-mlogloss:1.06375
[5]	validation_0-mlogloss:1.05786
[6]	validation_0-mlogloss:1.05182
[7]	validation_0-mlogloss:1.04634
[8]	validation_0-mlogloss:1.04096
[9]	validation_0-mlogloss:1.03565
[10]	validation_0-mlogloss:1.03048
[11]	validation_0-mlogloss:1.02570
[12]	validation_0-mlogloss:1.02084
[13]	validation_0-mlogloss:1.01627
[14]	validation_0-mlogloss:1.01183
[15]	validation_0-mlogloss:1.00767
[16]	validation_0-mlogloss:1.00361
[17]	validation_0-mlogloss:0.99949
[18]	validation_0-mlogloss:0.99551
[19]	validation_0-mlogloss:0.99162
[20]	validation_0-mlogloss:0.98797
[21]	validation_0-mlogloss:0.98451
[22]	validation_0-mlogloss:0.98121
[23]	validation_0-mlogloss:0.97793
[24]	validation_0-mlogloss:0.97499
[25]	validation_0-mlogloss:0.97206
[26]	validation_0-mlogloss:0.96925
[27]	validation_0-mlogloss:0.96654
[28]	validation_0-mlogloss:0.96392
[29]	validation_0-mlogloss:0.96156
[30]	validation_0-mlogloss:0.95910
[31]	validation_0-mlogloss:0.95651
[32]	validation_0-mlogloss:0.95416
[33]	validation_0-mlogloss:0.95175
[34]	validation_0-mlogloss:0.94942
[35]	validation_0-mlogloss:0.94727
[36]	validation_0-mlogloss:0.94508
[37]	validation_0-mlogloss:0.94296
[38]	validation_0-mlogloss:0.94099
[39]	validation_0-mlogloss:0.93903
[40]	validation_0-mlogloss:0.93715
[41]	validation_0-mlogloss:0.93540
[42]	validation_0-mlogloss:0.93353
[43]	validation_0-mlogloss:0.93181
[44]	validation_0-mlogloss:0.93000
[45]	validation_0-mlogloss:0.92835
[46]	validation_0-mlogloss:0.92677
[47]	validation_0-mlogloss:0.92512
[48]	validation_0-mlogloss:0.92366
[49]	validation_0-mlogloss:0.92206
[50]	validation_0-mlogloss:0.92047
[51]	validation_0-mlogloss:0.91890
[52]	validation_0-mlogloss:0.91741
[53]	validation_0-mlogloss:0.91594
[54]	validation_0-mlogloss:0.91449
[55]	validation_0-mlogloss:0.91308
[56]	validation_0-mlogloss:0.91186
[57]	validation_0-mlogloss:0.91062
[58]	validation_0-mlogloss:0.90947
[59]	validation_0-mlogloss:0.90819
[60]	validation_0-mlogloss:0.90690
[61]	validation_0-mlogloss:0.90572
[62]	validation_0-mlogloss:0.90450
[63]	validation_0-mlogloss:0.90334
[64]	validation_0-mlogloss:0.90230
[65]	validation_0-mlogloss:0.90116
[66]	validation_0-mlogloss:0.90000
[67]	validation_0-mlogloss:0.89892
[68]	validation_0-mlogloss:0.89784
[69]	validation_0-mlogloss:0.89681
[70]	validation_0-mlogloss:0.89578
[71]	validation_0-mlogloss:0.89482
[72]	validation_0-mlogloss:0.89388
[73]	validation_0-mlogloss:0.89302
[74]	validation_0-mlogloss:0.89208
[75]	validation_0-mlogloss:0.89130
[76]	validation_0-mlogloss:0.89058
[77]	validation_0-mlogloss:0.88989
[78]	validation_0-mlogloss:0.88903
[79]	validation_0-mlogloss:0.88840
[80]	validation_0-mlogloss:0.88770
[81]	validation_0-mlogloss:0.88707
[82]	validation_0-mlogloss:0.88622
[83]	validation_0-mlogloss:0.88557
[84]	validation_0-mlogloss:0.88492
[85]	validation_0-mlogloss:0.88431
[86]	validation_0-mlogloss:0.88379
[87]	validation_0-mlogloss:0.88326
[88]	validation_0-mlogloss:0.88262
[89]	validation_0-mlogloss:0.88221
[90]	validation_0-mlogloss:0.88166
[91]	validation_0-mlogloss:0.88098
[92]	validation_0-mlogloss:0.88040
[93]	validation_0-mlogloss:0.88000
[94]	validation_0-mlogloss:0.87927
[95]	validation_0-mlogloss:0.87868
[96]	validation_0-mlogloss:0.87820
[97]	validation_0-mlogloss:0.87771
[98]	validation_0-mlogloss:0.87718
[99]	validation_0-mlogloss:0.87664
[0]	validation_0-mlogloss:1.08908
[1]	validation_0-mlogloss:1.07998
[2]	validation_0-mlogloss:1.07143
[3]	validation_0-mlogloss:1.06330
[4]	validation_0-mlogloss:1.05557
[5]	validation_0-mlogloss:1.04817
[6]	validation_0-mlogloss:1.04112
[7]	validation_0-mlogloss:1.03439
[8]	validation_0-mlogloss:1.02800
[9]	validation_0-mlogloss:1.02203
[10]	validation_0-mlogloss:1.01616
[11]	validation_0-mlogloss:1.01045
[12]	validation_0-mlogloss:1.00497
[13]	validation_0-mlogloss:0.99988
[14]	validation_0-mlogloss:0.99494
[15]	validation_0-mlogloss:0.99038
[16]	validation_0-mlogloss:0.98607
[17]	validation_0-mlogloss:0.98202
[18]	validation_0-mlogloss:0.97801
[19]	validation_0-mlogloss:0.97409
[20]	validation_0-mlogloss:0.97046
[21]	validation_0-mlogloss:0.96693
[22]	validation_0-mlogloss:0.96361
[23]	validation_0-mlogloss:0.96025
[24]	validation_0-mlogloss:0.95703
[25]	validation_0-mlogloss:0.95411
[26]	validation_0-mlogloss:0.95124
[27]	validation_0-mlogloss:0.94854
[28]	validation_0-mlogloss:0.94585
[29]	validation_0-mlogloss:0.94329
[30]	validation_0-mlogloss:0.94076
[31]	validation_0-mlogloss:0.93839
[32]	validation_0-mlogloss:0.93611
[33]	validation_0-mlogloss:0.93372
[34]	validation_0-mlogloss:0.93152
[35]	validation_0-mlogloss:0.92941
[36]	validation_0-mlogloss:0.92753
[37]	validation_0-mlogloss:0.92579
[38]	validation_0-mlogloss:0.92405
[39]	validation_0-mlogloss:0.92245
[40]	validation_0-mlogloss:0.92084
[41]	validation_0-mlogloss:0.91923
[42]	validation_0-mlogloss:0.91772
[43]	validation_0-mlogloss:0.91633
[44]	validation_0-mlogloss:0.91467
[45]	validation_0-mlogloss:0.91300
[46]	validation_0-mlogloss:0.91145
[47]	validation_0-mlogloss:0.90985
[48]	validation_0-mlogloss:0.90814
[49]	validation_0-mlogloss:0.90668
[50]	validation_0-mlogloss:0.90521
[51]	validation_0-mlogloss:0.90404
[52]	validation_0-mlogloss:0.90306
[53]	validation_0-mlogloss:0.90177
[54]	validation_0-mlogloss:0.90067
[55]	validation_0-mlogloss:0.89946
[56]	validation_0-mlogloss:0.89864
[57]	validation_0-mlogloss:0.89780
[58]	validation_0-mlogloss:0.89668
[59]	validation_0-mlogloss:0.89603
[60]	validation_0-mlogloss:0.89531
[61]	validation_0-mlogloss:0.89436
[62]	validation_0-mlogloss:0.89355
[63]	validation_0-mlogloss:0.89285
[64]	validation_0-mlogloss:0.89189
[65]	validation_0-mlogloss:0.89111
[66]	validation_0-mlogloss:0.89045
[67]	validation_0-mlogloss:0.88981
[68]	validation_0-mlogloss:0.88905
[69]	validation_0-mlogloss:0.88838
[70]	validation_0-mlogloss:0.88758
[71]	validation_0-mlogloss:0.88706
[72]	validation_0-mlogloss:0.88643

In [79]:
opt_xgb_model = XGBClassifier(**study.best_params, eval_metric='mlogloss', enable_categorical=True)
opt_xgb_model.fit(X_train, y_train, eval_set=[(X_test, y_test)])

[0]	validation_0-mlogloss:0.99208
[1]	validation_0-mlogloss:0.97146
[2]	validation_0-mlogloss:0.95320
[3]	validation_0-mlogloss:0.93810
[4]	validation_0-mlogloss:0.92444
[5]	validation_0-mlogloss:0.91284
[6]	validation_0-mlogloss:0.90247
[7]	validation_0-mlogloss:0.89359
[8]	validation_0-mlogloss:0.88522
[9]	validation_0-mlogloss:0.87812
[10]	validation_0-mlogloss:0.87075
[11]	validation_0-mlogloss:0.86489
[12]	validation_0-mlogloss:0.85936
[13]	validation_0-mlogloss:0.85463
[14]	validation_0-mlogloss:0.84991
[15]	validation_0-mlogloss:0.84574
[16]	validation_0-mlogloss:0.84179
[17]	validation_0-mlogloss:0.83833
[18]	validation_0-mlogloss:0.83516
[19]	validation_0-mlogloss:0.83297
[20]	validation_0-mlogloss:0.83010
[21]	validation_0-mlogloss:0.82822
[22]	validation_0-mlogloss:0.82606
[23]	validation_0-mlogloss:0.82428
[24]	validation_0-mlogloss:0.82256
[25]	validation_0-mlogloss:0.82101
[26]	validation_0-mlogloss:0.82001
[27]	validation_0-mlogloss:0.81859
[28]	validation_0-mlogloss:0.81806
[29]	validation_0-mlogloss:0.81730
[30]	validation_0-mlogloss:0.81674
[31]	validation_0-mlogloss:0.81614
[32]	validation_0-mlogloss:0.81548
[33]	validation_0-mlogloss:0.81529
[34]	validation_0-mlogloss:0.81431
[35]	validation_0-mlogloss:0.81364
[36]	validation_0-mlogloss:0.81313
[37]	validation_0-mlogloss:0.81249
[38]	validation_0-mlogloss:0.81248
[39]	validation_0-mlogloss:0.81211
[40]	validation_0-mlogloss:0.81154
[41]	validation_0-mlogloss:0.81096
[42]	validation_0-mlogloss:0.81018
[43]	validation_0-mlogloss:0.81005
[44]	validation_0-mlogloss:0.80979
[45]	validation_0-mlogloss:0.80946
[46]	validation_0-mlogloss:0.80934
[47]	validation_0-mlogloss:0.80898
[48]	validation_0-mlogloss:0.80853
[49]	validation_0-mlogloss:0.80839
[50]	validation_0-mlogloss:0.80832
[51]	validation_0-mlogloss:0.80820
[52]	validation_0-mlogloss:0.80810
[53]	validation_0-mlogloss:0.80792
[54]	validation_0-mlogloss:0.80792
[55]	validation_0-mlogloss:0.80795
[56]	validation_0-mlogloss:0.80809
[57]	validation_0-mlogloss:0.80787
[58]	validation_0-mlogloss:0.80785
[59]	validation_0-mlogloss:0.80756
[60]	validation_0-mlogloss:0.80767
[61]	validation_0-mlogloss:0.80796
[62]	validation_0-mlogloss:0.80756
[63]	validation_0-mlogloss:0.80744
[64]	validation_0-mlogloss:0.80753
[65]	validation_0-mlogloss:0.80759
[66]	validation_0-mlogloss:0.80740
[67]	validation_0-mlogloss:0.80751
[68]	validation_0-mlogloss:0.80765
[69]	validation_0-mlogloss:0.80780
[70]	validation_0-mlogloss:0.80783
[71]	validation_0-mlogloss:0.80810
[72]	validation_0-mlogloss:0.80818
[73]	validation_0-mlogloss:0.80810
[74]	validation_0-mlogloss:0.80809
[75]	validation_0-mlogloss:0.80821
[76]	validation_0-mlogloss:0.80836
[77]	validation_0-mlogloss:0.80823
[78]	validation_0-mlogloss:0.80803
[79]	validation_0-mlogloss:0.80828
[80]	validation_0-mlogloss:0.80849
[81]	validation_0-mlogloss:0.80858
[82]	validation_0-mlogloss:0.80874
[83]	validation_0-mlogloss:0.80869
[84]	validation_0-mlogloss:0.80889
[85]	validation_0-mlogloss:0.80934
[86]	validation_0-mlogloss:0.80918
[87]	validation_0-mlogloss:0.80928
[88]	validation_0-mlogloss:0.80953
[89]	validation_0-mlogloss:0.80983
[90]	validation_0-mlogloss:0.80994
[91]	validation_0-mlogloss:0.81018
[92]	validation_0-mlogloss:0.81043
[93]	validation_0-mlogloss:0.81073
[94]	validation_0-mlogloss:0.81101
[95]	validation_0-mlogloss:0.81123
[96]	validation_0-mlogloss:0.81157
[97]	validation_0-mlogloss:0.81161
[98]	validation_0-mlogloss:0.81169
[99]	validation_0-mlogloss:0.81200

XGBClassifier(alpha=0.07748038999606824, base_score=None, booster=None,
              callbacks=None, colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.07820384905439096,
              max_bin=712, max_cat_threshold=28, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=8, max_leaves=179,
              min_child_weight=0.017027577032364988, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, ...)

In [80]:
y_prob = opt_xgb_model.predict_proba(X_test)   # shape (n_samples, 3) — then argmax makes sense
y_pred = opt_xgb_model.predict(X_test)          # shape (n_samples,) — class labels directly


qwk = cohen_kappa_score(y_test, y_pred, weights='quadratic')
print(f"QWK: {qwk:.4f}")
print(classification_report(y_test, y_pred, target_names=['Poor', 'Standard', 'Good']))
print(confusion_matrix(y_test, y_pred))

QWK: 0.5000
              precision    recall  f1-score   support

        Poor       0.63      0.54      0.59       901
    Standard       0.63      0.74      0.68      1621
        Good       0.57      0.43      0.49       603

    accuracy                           0.62      3125
   macro avg       0.61      0.57      0.59      3125
weighted avg       0.62      0.62      0.62      3125

[[ 490  374   37]
 [ 269 1196  156]
 [  15  328  260]]

In [81]:
auc = roc_auc_score(y_test, y_prob, multi_class='ovr')
print(f"AUC: {auc:.4f}")

AUC: 0.7784

In [ ]:
# from sklearn.calibration import calibration_curve
# import matplotlib.pyplot as plt

# for i, label in enumerate(['Poor', 'Standard', 'Good']):
#     prob_true, prob_pred = calibration_curve(
#         (y_test == i).astype(int), probs[:, i], n_bins=10
#     )
#     plt.plot(prob_pred, prob_true, marker='o', label=label)

# plt.plot([0, 1], [0, 1], '--', color='grey', label='Perfect')
# plt.xlabel('Mean predicted probability')
# plt.ylabel('Fraction of positives')
# plt.legend()
# plt.title('Calibration curves')
# plt.show()

In [ ]:
# importances = final_xgb.feature_importances_   # or model.feature_importance(importance_type='gain') for LightGBM
# feature_names = X.columns

# importance_df = pd.DataFrame({
#     'feature': feature_names,
#     'importance': importances
# }).sort_values('importance', ascending=False)

# # Normalize to sum to 100 for easy reading
# importance_df['importance_pct'] = 100 * importance_df['importance'] / importance_df['importance'].sum()

# print(importance_df.head(20).to_string(index=False))

## Deep Learning - MultiClass Classification

In [ ]:
data_dl = user_history.drop(columns = ['Customer_ID', 'order', 'mix_target', 'latest_month'])

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
from sklearn.preprocessing import StandardScaler

In [ ]:
import random

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [ ]:
num_cols = data_dl.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = data_dl.select_dtypes(include=['object', 'string', 'category']).columns.tolist()

In [ ]:
cat_cols.remove('Target')
cat_cols

['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount', 'Payment_Behaviour']

In [ ]:
# Ordinal encoding — preserve the natural order
label_map = {"Poor": 0, "Standard": 1, "Good": 2}
data_dl["Target_label"] = data_dl["Target"].map(label_map)

In [ ]:
target_cols = ['Target_label']

In [ ]:
from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight= 'balanced',
    classes=np.array([0, 1, 2]),
    y=data_dl["Target_label"].values
)
class_weights = torch.tensor(class_weights, dtype=torch.float32)
# Pass into loss function — model pays more attention to rare classes
criterion = nn.CrossEntropyLoss(weight=class_weights)

In [ ]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [ ]:
X_train, X_test , y_train , y_test = train_test_split(
    data_dl.drop(columns=target_cols),
    data_dl[target_cols],
    test_size=0.25,
    random_state=42,
    stratify=data_dl[target_cols]
)

In [ ]:
label_encoder = LabelEncoder().fit(data_dl[cat_cols].values.ravel())
scaler = StandardScaler().fit(X_train[num_cols])

In [ ]:
## Creating Custom DataSet
class HistDataset(Dataset):
    def __init__(self, df, cat_cols, cont_cols, label_col, scaler, label_encoder):
        self.cat_data = df[cat_cols].copy()
        self.cont_data = df[cont_cols].copy()
        self.labels = df[label_col].values

        # Apply label encoders
        for col in cat_cols:
            self.cat_data[col] = label_encoder.transform(self.cat_data[col].astype(str))

        # Apply scaler
        self.cont_data = scaler.transform(self.cont_data)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        cat = torch.tensor(self.cat_data.iloc[idx].values, dtype=torch.long)
        cont = torch.tensor(self.cont_data[idx], dtype=torch.float32)
        label = torch.tensor(self.labels[idx], dtype=torch.long)
        return cat, cont, label

In [ ]:
train_set = HistDataset(X_train, cat_cols, num_cols, 'Target_label', scaler, label_encoder)
val_set = HistDataset(X_test, cat_cols, num_cols, 'Target_label', scaler, label_encoder)